### ISSUE TITLE
태그 모음 페이지에 제목이 길면 배경 길이가 안맞습니다.

### ISSUE THREAD

**Issue by wjnoh** [velopert/velog-client#100]
![image](https://user-images.githubusercontent.com/26599345/75647631-ee394c80-5c90-11ea-818e-7f4fc7ebd0bb.png)

https://velog.io/tags?sort=alphabetical
배경의 height가 고정돼있어서 제목이 길면 길이가 안맞네요.

**Comment by velopert** [comment]
이게 일부 사용자들이 태그를 제대로 등록하지 않아서그런건데
저런식으로 작성해도 정상적으로 작동하게끔 수정하겠습니다.

**Comment by velopert** [comment]
이미 존재하는 태그들은 수동작업으로 처리 할 예정입니다.
