### ISSUE TITLE
태그별 포스트 count 버그 제보드립니다.

### ISSUE THREAD

**Issue by MinhoLee93** [velopert/velog-client#104]
안녕하세요? :)
소소하게 찾아낸 버그 제보드립니다.

✔ 문제 : 태그의 총 포스트 갯수 count의 값 mapping이 중복됨

버그 상황 순서대로 캡처해보았습니다.

1) 전체 태그 목록 조회  : 현재 aws의 포스트 갯수 116개

![image](https://user-images.githubusercontent.com/50879621/75963577-14692180-5f09-11ea-9ce5-bbb9a956f899.png)

2) aws 태그 클릭해 관련 포스트 목록 조회 -> 유저 상세 페이지로 이동

![image](https://user-images.githubusercontent.com/50879621/75963753-6611ac00-5f09-11ea-9f94-41a50b453417.png)

3) 유저의 현재 aws 태그 포스트 갯수 24개

![image](https://user-images.githubusercontent.com/50879621/75963847-935e5a00-5f09-11ea-8116-288e203a0727.png)

4) 현 상태에서 다시 전체 태그 목록조회시 태그의 포스트 갯수가 24개로 나옴

![image](https://user-images.githubusercontent.com/50879621/75964134-05cf3a00-5f0a-11ea-8e2f-24d9da99c3e8.png)

위의 값은 새로고침해야 정상적으로 돌아옵니다.

**Comment by velopert** [comment]
서버 이슈 쪽으로 해결해야 할 것 같아서 여기서 닫고 서버측에 새로 이슈 만듭니다 :)
