### ISSUE TITLE
비로그인 상태 댓글작성

### ISSUE THREAD

**Issue by ljlm0402** [velopert/velog-client#106]
비로그인 상태로 포스팅에 댓글을 달려고하면 아무동작이 일어나지 않습니다.

▾ 개발자 모드 - console

![image](https://user-images.githubusercontent.com/42952358/76040960-3e1b5a80-5f94-11ea-8cbe-2624b3701e3a.png)

개발자 모드에서는 로그인이 안되었다는 콘솔이 나타나지만 개발자가 아닌 일반 사용자분들에게는 불편할거 같습니다. 로그인 모달창을 나타내는 방법이 개인적으로 좋다고 생각합니다.
우선 주제넘게 참견한점에 대해 진심으로 사죄의 말씀을 드립니다. 너무나 존경하는 개발자이시면서 좋은 서비스를 만들어주셔서 감사합니다.

**Comment by velopert** [comment]
ㅎㅎ 당당히 참견하셔도 됩니다..! 그러라고 있는 Issue 니까요~ 
추후 수정하도록 하겠습니다.
