### ISSUE TITLE
마크다운 취소선이 제대로 동작하지 않는 것 같습니다.

### ISSUE THREAD

**Issue by DrakedogX** [velopert/velog-client#107]
<img width="228" alt="스크린샷 2020-03-10 오전 11 18 51" src="https://user-images.githubusercontent.com/11283675/76273544-74711680-62c1-11ea-87bc-1f32f83ac3f1.png">

~~ ~~
요 문법인데요

아무래도 이상해서 처음엔 웹 브라우저나 OS 문제인가 싶었지만...

스크린샷처럼 취소선이 제대로 표시가 안되네요....ㅠ

**Comment by velopert** [comment]
감사합니다 ^^ 반영됐습니다.
