### ISSUE TITLE
글쓰기 시 마이너 이슈 

### ISSUE THREAD

**Issue by retinan** [velopert/velog-client#113]
아무글이나 
- 아무글이나 쓰자

abc 
- abcdef

텍스트 
- 텍스트 텍스트 

위와 같은 형태로 텍스트 다음 줄 - (하이픈)을  작성하면 텍스트가 커졌다가 글을 이어 작성하면 다시 원래대로 돌아옵니다.

**Comment by velopert** [comment]
```
Heading1
=

Heading2
-
```


Heading1
=

Heading2
-

**Comment by velopert** [comment]
조금 이상하긴 하지만 ㅎㅎ 마크다운 스펙입니다.
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers
