### ISSUE TITLE
태그를 붙여 작성할 경우 오류 발생합니다.

### ISSUE THREAD

**Issue by beckyi** [velopert/velog-client#118]
안녕하세요. 오류 확인 부탁드립니다.

p 태그 내 글을 작성하는 도중 <code> 입력 시 오류가 발생합니다.

작성이 된 글에 태그를 붙일 경우 발생하는 것 같습니다.
 '<co' 까지 입력 후 스크립트 에러가 발생합니다.

사진 같이 첨부합니다. 감사합니다.

- 첨부 사진
<img width="1280" alt="스크린샷 2020-03-17 오전 7 44 01" src="https://user-images.githubusercontent.com/18224086/76805835-450f5c00-6823-11ea-942f-6fa14c93e688.png">

**Comment by velopert** [comment]
#93 
조만간 고치겠습니다 :D 
해당 이슈 링크해놓고 이 이슈는 닫을게요~
