### ISSUE TITLE
수식입력 기능 문의

### ISSUE THREAD

**Issue by lee-zion** [velopert/velog-client#119]
우선, velog를 정말 즐겨 보고 있습니다. 감사합니다.

수식입력 기능은 제가 포스팅을 써보려고 했을 때, 관련 내용으로 여러 수식을 입력하고 싶었는데 [katex](https://katex.org/)같이 수식편집을 지원하지 않아 수식을 이미지파일로 변환 후에 작성을 하고 있습니다.

혹시 수식편집 기능이 있다거나, 없다면 관련 기능을 추가할 계획이 있으신지 궁금합니다.

**Comment by velopert** [comment]
기존에 비슷한 이슈가 올라온게 있어서 #5 닫습니다.
