### ISSUE TITLE
이미지 엑박

### ISSUE THREAD

**Issue by CODEMCD** [velopert/velog-client#121]
안녕하세요 벨로퍼트님
velog v1에서 작성했던 글을 다시 읽어보다가 버그를 발견하여 글을 쓰게 되었습니다. 다른 글들은 괜찮은데 이 글에서만 대부분의 이미지가 액박으로 뜹니다.
- [이슈가 생긴 글 링크](https://velog.io/@codemcd/%EC%84%B8%EB%AF%B8%EB%82%98%EC%95%A0%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98%EC%99%80-%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5-By-%EC%A1%B0%EC%98%81%ED%98%B8-ruk38dmck3)

![velog image issue 2](https://user-images.githubusercontent.com/34755287/76941233-ffe04c80-693e-11ea-9ca2-62dd4fb86ecb.png)
---
![velog image issue 1](https://user-images.githubusercontent.com/34755287/76941220-fb1b9880-693e-11ea-93e5-a1f9ad58b25c.png)

글 작성 페이지의 미리보기에서는 위와 같이 정상적으로 이미지가 뜹니다.(모든 이미지가 미리보기에서는 정상적으로 뜹니다.) 그리고 아래와 같은 실험을 해보았습니다.
- 위 엑박이 뜨는 이미지가 썸네일로 설정되었는데, 글에서는 이 썸네일도 엑박으로 보입니다.
- 엑박이 뜨는 이미지를 새로 삽입해보았을 때도 같은 이슈가 발생하였습니다.
- 엑박이 뜨는 이미지 이름을 영어와 숫자로만 이루어지도록 변경하여 삽입하였을 때도 같은 이슈가 발생하였습니다.
- 같은 이미지를 새로 스크린샷으로 찍어 삽입해보았는데 같은 이슈가 발생하였습니다.
- 위 이슈로 찍은 스크린샷 이미지를 삽입해보았는데 정상적으로 이미지가 나왔습니다.
- 엑박뜬 이미지보다 사이즈가 큰 다른 이미지를 삽입했을 때도 정상적으로 이미지가 나왔습니다.

엑박이 뜨는 이미지와 정상적으로 뜨는 이미지와 비교해봐도 차이점을 잘 모르겠네요...

**Comment by velopert** [comment]
#122 
이슈 해결했습니다. 현재 CDN 비용을 낮추기 위하여 이미지를 리사이즈 하고 있는데
이미지를 리사이즈 했을 때 1MB 이상의 크기가 나오면 오류가 발생합니다.

그래서, 포스트에서 이미지 리사이즈를 하지 않고 Cloudflare CDN으로 교체를 해봤습니다.
이렇게 했을 때 비용이 어떻게 나오는지 알아보고..  비용이 너무 많이 나오면 다른방식으로 또 해결해보게 될 것 같네요 :)

**Comment by CODEMCD** [comment]
감사합니다!
