### ISSUE TITLE
velog.io/@username에서의 404 페이지 오류

### ISSUE THREAD

**Issue by ilcm96** [velopert/velog-client#129]
### ENV
- Windows 10 19H2
- FHD 24"

---
velog.io/@username에서 존재하지 않는 username을 넣고 접속하면 아래와 같이 404 페이지가 깨져서 나옵니다.
![username404](https://user-images.githubusercontent.com/20370957/77409330-657b7f80-6dfc-11ea-9d21-0635bdaa7ed6.PNG)

아래는 정상적인 404 페이지의 모습입니다.
![normal404](https://user-images.githubusercontent.com/20370957/77409307-5f859e80-6dfc-11ea-8de2-2a62345c91e3.PNG)

**Comment by velopert** [comment]
원인을 분석하여 내일 중으로 배포될 예정입니다 :)
이전부터 왜 그런거지? 싶었는데.. ㅋㅋㅋ 오늘 자세히 코드 보고 원인을 드디어 알아냈네요~
