### ISSUE TITLE
code inline(` `) 모양을 선택할 수 있으면 좋겠습니다!

### ISSUE THREAD

**Issue by CreamPuffx2** [velopert/velog-client#149]
현재는 형광펜 하이라이팅처럼 되어 있는데
정말 '하이라이팅'만 된 거 같은 느낌이라
개인적으로 코드다워 보이지 않는 것이 조금 아쉬웠습니다.

개발 입문하고 velog를 정말 잘 사용하고 있습니다!
항상 감사합니다^^

**Comment by velopert** [comment]
그렇군요 :)
지금 당장은 인라인 코드의 스타일을 사용자가 직접 고르게하는건 힘들 것 같고
피드백을 반영하여 인라인 코드 스타일이 하이라이팅이 아닌 실제 코드답게 보여주는게 좋을 것 같습니다.
혹시, 추천할만한 스타일 및 참고하면 좋을 것 같은 웹페이지가 있을까요?

아니면, 그냥 github 스타일 그대로 할까요? ㅎㅎ `이렇게`

**Comment by CreamPuffx2** [comment]
넵 깃헙 스타일이 가장 무난할 것 같습니다ㅎㅎ
답변 감사합니다:)
