### ISSUE TITLE
덧글의 개수가 표시되어 있으나 덧글이 없는 증상

### ISSUE THREAD

**Issue by WonHeeSoo** [velopert/velog-client#150]
![이미지](https://github.com/WonHeeSoo/About-My-Velog/blob/master/Images/Bug/CommentBug.PNG?raw=true)

덧글은 1개라고 되어 있으나 정작 아무 덧글도 없습니다.

예상하기로는 해당 [게시물](https://velog.io/@wonhs717/%EB%A7%88%ED%81%AC%EB%8B%A4%EC%9A%B4Markdown-%EB%AC%B8%EB%B2%95-ytk5zemk0x)에 섬네일 이미지를 어떻게 추가하는지 질문 덧글이 있었고 제가 그것에 답변을 달았었습니다.

그런데 덧글을 다신 분께서 velog 계정을 탈퇴한 건지 혹은 덧글을 삭제한건지 없어졌으나 답글은 남아있어 보이지는 않지만 1개라고 표시되어 있는 것 같습니다.

**Comment by velopert** [comment]
허허.. 이런 버그가 있군요!

**Comment by velopert** [comment]
탈퇴 할 때 이러한 문제가 발생하는것 같습니다! ㅠㅠ
서버 이슈로 이전하겠습니다~

유령 댓글은 제가 직접 삭제처리하였구요
추후 탈퇴처리할때 댓글이 deleted 상태로 매끄럽게 이루어지도록 만들고
유령 댓글을 일괄적으로 삭제하는 작업을 해야 될 것 같네요!
