### ISSUE TITLE
로그인 유지 기능

### ISSUE THREAD

**Issue by Whis-dev** [velopert/velog-client#152]
여러탭에 벨로그 글들을 띄워놨을 경우, 각 탭마다 로그인을 해야하는 불편이 있습니다.
예를 들어 해당 글이 마음에 들어 하트를 누를 경우, 한번 로그인이 되면 보통 다른 탭에 있는 벨로그 들도 로그인이 유지되어 이후에는 따로 로그인을 하지 않아도 되었으면 조금더 편리 할 것같습니다.

UI도 매우 깔끔하고 좋아서 애용하고 있습니다 :D
좋은 서비스 만들어주셔서 정말 감사합니다.

**Comment by velopert** [comment]
혹시 사용중인 브라우저를 알 수있을까요?
로그인 유지 기능은 기본적으로 적용이 되어있는데
신기하네요..!

**Comment by Whis-dev** [comment]
크롬에서 쓰고 있었는데, 지금 보니 다시 잘 되는 것 같습니다.
벨로그 글들을 여러탭에 한번에 띄우고 볼때 생겼었는데, 그 때 당시 캐시가 없었거나 했었나봐요.
흠... 그렇다고 해도, 그 때도 다시 로그인 했을 때 로그인 유지가 되어야했었을 텐데 저도 조금 신기하기는 합니다.

**Comment by velopert** [comment]
그렇군요! 일단 닫아두겠습니다. ㅠㅠ 저도 재현 할 방법을 잘 모르겠더라구요..
비슷한 이슈 또 발생하면 열어주세요~
