### ISSUE TITLE
설정 - 소셜정보 - 블로그 건의

### ISSUE THREAD

**Issue by Limm-jk** [velopert/velog-client#153]
소셜정보를 입력하는 칸에 블로그를 입력하면 아래와 같이 연결이 되는 것을 확인했습니다.
> https://velog.io/블로그주소

블로그로 velog를 하나 더 사용할 수도 있지만 다른 TIL용이나 개인 사이트를 연동하시는 분들을 위해 바로 블로그 주소로 연결되었으면 좋겠습니다.

velog 너무 잘 쓰고 있습니다. 감사합니다!

**Comment by velopert** [comment]
앞부분에 `https://` 를 포함시키면 잘 작동할것입니다.
그게 없을때 상대경로로 이동되는 버그네요 이건 ㅎㅎ 조만간 고칠게요!
