### ISSUE TITLE
파이어폭스에서 글을 쓸 때 이상한 현상이 발생합니다.

### ISSUE THREAD

**Issue by jinyongp** [velopert/velog-client#155]
![velog_firefox_malfunction](https://user-images.githubusercontent.com/21158729/78894911-e8613300-7aa8-11ea-80e4-d7105d7399ec.gif)

**저는 여기서 백스페이스를 일절 누른 적이 없습니다.**

글자 쓰고 밑줄이 있는 상태에서 드래그하는대로 글자가 다 지워져요. ESC를 누르기 전까지 상태가 지속되요.그런데 스페이스바를 눌러서 밑줄이 없어진 상태가 되면 그땐 안 그래요.  velog에서 댓글이나 다른 거 쓸 땐 아무 문제 없어요. 제목 쓸 때도 문제 없고요. 글 쓸 때만 그러네요...

크롬에선 또 괜찮네요... 이게 엄청 불편해서 글 쓰다가 ctrl z를 몇 번이나 누르는지 ㅜㅜ 혹시 velog 크롬 최적화인가요? 그럼 죄송합니다...

**Comment by velopert** [comment]
불편을드려 죄송합니다.. ㅠㅠ
조사해보겠습니다!
