### ISSUE TITLE
글서식(인용문, 인라인 코드) 관련 깨짐

### ISSUE THREAD

**Issue by whghdus17** [velopert/velog-client#16]
인용문과 인라인코드의 표기 방식이 바뀐건지, 에러인건지 정확하지 않은데 기존에 표기 방식으로 보이지 않고 깨져서 보입니다.

**Comment by velopert** [comment]
인용문 부분 스타일 적용 됐습니다.

인라인 코드는 문제 없는 것 같은데..
아직도 이슈가 존재한다면 아시 이슈 open 하고 스크린샷 올려주시겠어요?

감사합니다.
