### ISSUE TITLE
표 정렬이 적용되지 않습니다.

### ISSUE THREAD

**Issue by jinyongp** [velopert/velog-client#162]
![image](https://user-images.githubusercontent.com/21158729/79678198-ce0b2000-8233-11ea-98bd-d2f02f27f993.png)

미리보기에서는 잘 적용된 듯 보이지만,

![image](https://user-images.githubusercontent.com/21158729/79678235-293d1280-8234-11ea-9c77-e7924e0929fd.png)

언젠가부터 정렬이 제대로 적용되질 않네요.

**Comment by velopert** [comment]
마크다운 표에 정렬하는 기능이 있는지 방금 알았습니다 :o
고쳐보도록 하겠습니다 !
