### ISSUE TITLE
velog에 문의드립니다

### ISSUE THREAD

**Issue by Helena360** [velopert/velog-client#163]
안녕하세요:) 

Velog.io에 온라인 광고 게재 관련하여 제안드리고자 문의남깁니다. 
저는 optAd360의 한국 대표 퍼블리셔 서비스 매니저 황효정입니다. 
현재 Velog 웹사이트에 광고는 아직 적용되지 않은 것을 확인하였습니다:) 

저희는 구글 애드매니저 파트너사로서, 웹사이트 내 광고 게재하셨을 때 가장 수익적으로 효율이 좋은 구간을 AI인공지능 엔진으로 분석하여 광고 레이아웃을 제안드립니다. 현재 57개국 2000여개 이상의 도메인들과 협력하고 있으며, 대형 미디어 하우스를 비롯하여 전문지, 커뮤니티 웹사이트 등 다양한 분야의 웹사이트에 유저 경험을 고려한 맞춤형 광고를 컨설팅을 통해 제공드리고 있습니다. 

보다 가시적인 수익적 성과를 확인하실 수 있게 Velog에 한 달 서비스 체험권을 제안드립니다. 
하나 또는 두개의 유닛으로 테스트해보실 수 있으며, 수익금또한 당연히 퍼블리셔님께 지급됩니다. 

웹사이트 컨텐츠와 레이아웃이 정말 좋아서, 저희 서비스 이용하실 경우 분명히 수익적으로 성과가 있을 것입니다. 문의사항은 hyojung.hwang@optad360.com으로 편하게 말씀주세요:) 
친절하고 정성껏 답변드리겠습니다. 

봄비내리는 월요일에 상쾌한 하루 되시길 바랍니다,
감사합니다

황효정 올림

**Comment by velopert** [comment]
광고 관련해서는 현재 고민중에 있는데..
추후 광고를 도입하게 될 때 연락드리도록 하겠습니다.

공식 메일은 contact@velog.io 입니다. 

감사합니다.
