### ISSUE TITLE
시리즈 잘못추가 한것 같은데 혹시 삭제기능 혹은 수정 기능이 있을가요??

### ISSUE THREAD

**Issue by daonez** [velopert/velog-client#166]
안녕하세요 벨로그 정말 사용하기 편하고, ui ux 도 나쁘지 않다고 생각하게 되어 사용하게 되었습니다..
몇일전에 잘못눌러서 빈 시리즈를 추가하였고..생각보다 눈에 자꾸 띄어서 너무너무 삭제하고싶습니다... 혹시 이러한 기능이 따로 있는지 궁금해서 질문올려봅니다^^;; 

![126512626](https://user-images.githubusercontent.com/48469471/81042765-c8783000-8eeb-11ea-82e2-25fb93ebcc97.png)
![asfasf](https://user-images.githubusercontent.com/48469471/81042767-c9a95d00-8eeb-11ea-8afb-4d07c86f198d.png)

**Comment by velopert** [comment]
![image](https://user-images.githubusercontent.com/17202261/81350292-91c53400-90fc-11ea-915b-0135dccd1b7d.png)
해당 비어있는 시리즈에 들어가시면 상단에 삭제 버튼이 있습니다.
