### ISSUE TITLE
빈 내용으로 댓글 작성시 '삭제된 댓글 입니다'

### ISSUE THREAD

**Issue by Choi-Jinwoo** [velopert/velog-client#168]
빈 내용으로 댓글 작성하기 클릭시 '삭제된 댓글 입니다' 라고 뜸

**Comment by velopert** [comment]
아 ㅋㅋ 삭제된 댓글이라고 뜨는 이유가 이거였군요!
빈 내용 댓글 일괄 삭제하고 앞으로는 에러처리해야겠네요~
