### ISSUE TITLE
`blockquote` 내에서 체크박스 적용이 안 됩니다

### ISSUE THREAD

**Issue by cadenzah** [velopert/velog-client#169]
[이 글](https://velog.io/@cadenzah/graphql-node-10-summary)인데요~

![image](https://user-images.githubusercontent.com/18698124/81259433-e91ec200-9072-11ea-8dcc-17fe349c892a.png)

작성 중인 에디터 상에서는 프리뷰에서 정상적으로 잘 나옵니다.

![image](https://user-images.githubusercontent.com/18698124/81259457-f3d95700-9072-11ea-8f5d-dc63a519a3f8.png)

실제 글에서는 단순 unordered list로 출력이 되어요.

**Comment by velopert** [comment]
아하, HTML sanitize 과정에서 생긴것같은데 검토하겠습니다.
