### ISSUE TITLE
글 오른쪽 차례가 길어지면 짤리는 현상

### ISSUE THREAD

**Issue by Sungmin-Kim-0508** [velopert/velog-client#18]
![image](https://user-images.githubusercontent.com/37981164/74117445-b1909e80-4b85-11ea-8b5f-7ad85c8b0db1.png)

벨로퍼트님이 쓴 글 [TypeScript 환경에서 Redux를 프로처럼 사용하기](https://prod.velog.io/@velopert/use-typescript-and-redux-like-a-pro#%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B3%A0-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0)을 캡처한 사진인데 오른쪽의 차례가 밑에 짤려있습니다.  차례가 짧으면 괜찮은데 길어지면 짤리는 것 같습니다

**Comment by Danue1** [comment]
혹시 v1 때에는 어떻게 보였는지 알 수 있을까요?

**Comment by Sungmin-Kim-0508** [comment]
v1 때 캡처한 사진이 없지만 v1때에는 맨 마지막 h1까지는 보였던걸로 기억합니다

**Comment by Danue1** [comment]
목차(ToC)를 스크롤 할 수 있도록 하는 PR 올렸습니다.
