### ISSUE TITLE
[기능 건의] Organization 시스템

### ISSUE THREAD

**Issue by roeniss** [velopert/velog-client#185]
제가 생각하는 것은 Medium 블로그처럼 organization 개념을 도입해서,

해당 그룹에 속한 사람들이 각자 글을 작성할 때 본인이 속한 Organization에 공유 O/X를 결정하고,

이후 velog.io/organization/@myOrg 로 접속하면 공유 O인 글들이 모여있는 형태입니다.

**Comment by velopert** [comment]
좋은 기능이라고 생각합니다!
기업 블로그같은걸 운영할때 정말 좋을 것 같아요.
기능을 언젠가 만들려고 했는데 그 주소와 구조를 어떻게 하는게 좋을까 고민했었는데
말씀해주신 형태가 참 좋을것같네요~! 추후 기능 개발할때 참고하겠습니다.
