### ISSUE TITLE
모바일 화면에서는 게시글 추천(하트) 버튼이나 공유버튼이 없습니다.

### ISSUE THREAD

**Issue by junwoochoi** [velopert/velog-client#19]
![image](https://user-images.githubusercontent.com/26688947/74120649-6d45e280-4c07-11ea-8969-83b19cdb3fda.png)

의도하신 바인지는 모르겠지만, 모바일로는 게시글 추천이 불가능합니다. 😭

**Comment by velopert** [comment]
오우..?! 의도한게 아닙니다. ㅋㅋㅋ 고쳐야지요!

**Comment by velopert** [comment]
모바일 Share 는 추후 만들 계획입니다 (급한것같지는 않아서 - 그래서 새로운 이슈 만들도록 할게요)
