### ISSUE TITLE
제목에 특수문자 하나들어갔을경우

### ISSUE THREAD

**Issue by hyeony** [velopert/velog-client#196]
혼자서 글 작성 테스트하다가
포스팅 제목을 . <- 마침표 하나 적고 출간하기했더니
해당 포스팅으로 페이지가 생성이안된걸까요..
클릭도안되고 ㅠㅠ.. 페이지로 넘어가지도않습니다.

**Comment by velopert** [comment]
고쳐졌습니다 :) 너무 늦게 고쳤네요 하하..
