### ISSUE TITLE
[기능제안] 구글 애널리틱스 기능 추가

### ISSUE THREAD

**Issue by bingbing-ba** [velopert/velog-client#203]
안녕하세요 velopert님

혹시 velog 사용자마다 구글 애널리틱스를 적용할 수 있게 기능 개선을 할 계획은 없으신가요?

통계 기능 때문에 사용하던 velog를 떠나 
medium, tistory, 네이버 등 다른 블로그 플랫폼을 아무리 찾아봐도
이 곳의 간결한 디자인 때문에 다시 돌아오고 싶은 마음이 굴뚝 같습니다ㅠㅠ

혹 계획이 있다면 언제쯤이 될 지 알려주시면 감사드리겠습니다.

velog를 잘 사용하고 있습니다. 감사드립니다!

**Comment by velopert** [comment]
애널리틱스는 사용자마다 도메인을 다르게 설정하지 않는이상 어려울것같아요.
다만, 각 포스트의 조회수 통계를 확인할수있도록 했답니다 :)
