### ISSUE TITLE
게시글 작성 시, 비공개로 자동 전환

### ISSUE THREAD

**Issue by minssseo** [velopert/velog-client#248]
velog에 게시글 작성 시, 전체 공개로 출간하였는데,
자동으로 비공개 전환이 되어 외부에서 접근 불가능한 게시글이 있습니다.

혹시 글 내부적으로 문제가 있어서 자동으로 비공개로 출간이 되는건가요?

**Comment by GentleDot** [comment]
저도 동일 문제가 있어 댓글 남깁니다. 
게시글 내용이 일정 길이 넘어가면 자동으로 비공개로 설정되어 버리는데 내용을 나눠서 올리기도 뭐하고...
버그 확인 부탁드릴께요.

**Comment by june0122** [comment]
저도 현재 동일한 증상을 겪고 있어서 내용 수정을 계속해보았는데도 원인을 잘 모르겠습니다 ㅠㅠ

버그 확인 부탁드립니다!!

**Comment by o-ddong** [comment]
저두요!!! 같은 현상 있습니다ㅜㅜ

**Comment by sawol** [comment]
저도 같은 문제였는데 글에 `password`라는 키워드가 들어있어서 비공개로 자동 전환되는거였네요....

**Comment by velopert** [comment]
불편을 드려 죄송합니다.
스팸 글 필터링 하는 과정에서 규칙이 좀 강하게 들어갔었습니다 ㅎㅎ;
조금 완화하였습니다.

감사합니다.

**Comment by Kayoungkimjs** [comment]
여전히 `center` 작성시 비공개 처리가 됩니다.ㅜ

**Comment by jayarnim** [comment]
어제부로 서포트 벡터 머신 관련 포스팅 업로드 시 비공개에서 전체공개로 변경이 되지 않는 문제가 발생하고 있습니다. 혹시 저만 겪고 있는 문제인지 벨로그 전체의 문제인지 궁금하여 메시지 남깁니다..!
