### ISSUE TITLE
이미지파일이 정상적으로 불러와지는지?

### ISSUE THREAD

**Issue by bathingape** [velopert/velog-client#25]
링크로만보이내요

**Comment by velopert** [comment]
혹시 스크린샷을 보여주실 수 있을까요?
어떻게하면 재현 할 수 있을까요?

**Comment by bathingape** [comment]
![image](https://user-images.githubusercontent.com/53068281/74151426-82466400-4c4f-11ea-94cc-a05aa22b8638.png)

**Comment by bathingape** [comment]
정상적으로 되는 이미지도 있습니다.

**Comment by velopert** [comment]
이 부분은 벨로그 문제는 아니고,

![image](https://user-images.githubusercontent.com/17202261/74155096-42837a80-4c57-11ea-8866-7ef93f817ccb.png)


우측에 있는  ```를 여백을 다 지워서 왼쪽으로 두시면 코드 블록이 닫아지면서 정상적으로 나오게 될 것입니다.

이슈는 닫을게요~
