### ISSUE TITLE
[질문] 댓글에 공백이 생깁니다.

### ISSUE THREAD

**Issue by HTMLhead** [velopert/velog-client#26]
안녕하세요. 항상 작성해주시는 리액트 관련 강의 재미있고 유익하게 잘 보고 있습니다.
velog라는 좋은 서비스를 무료로 사용할 수 있도록 만들어 주셔서 감사합니다!

다름이 아니고, 개편된 이후 댓글에 공백이 생깁니다. 상태는 아래와 같습니다.
 
<img width="1095" alt="스크린샷 2020-02-10 오후 8 35 00" src="https://user-images.githubusercontent.com/40166539/74146683-01826a80-4c45-11ea-8db6-4ca84c341b0a.png">

제 생각엔 아래와 같이 보이는게 더 읽기 편한 것 같아서요.

<img width="1096" alt="스크린샷 2020-02-10 오후 8 34 41" src="https://user-images.githubusercontent.com/40166539/74146677-ffb8a700-4c44-11ea-8339-1f616785cc17.png">

혹시 의도하신 동작이신지, 아니라면 혹시 제가 부족한 실력이지만 풀 리퀘스트를 보내도 되는지 궁금합니다.
시간내서 읽어주셔서 감사합니다 😄❤️

**Comment by velopert** [comment]
감사합니다 :)

풀 리퀘스트를 보내주셔도 되지만 - 이번엔 직접 고쳤습니다!
추후 PR 에 대한 가이드를 준비해놓도록 하겠습니다!

**Comment by HTMLhead** [comment]
정말 빠른 반영 감사드립니다 👍
