### ISSUE TITLE
개인 '설정' 페이지 이메일 주소 문제?

### ISSUE THREAD

**Issue by ddarkr** [velopert/velog-client#29]
![image](https://user-images.githubusercontent.com/6638675/74156695-3816b000-4c5a-11ea-8949-8858cc881292.png)

버그(?)가 있는거 같아요. 이메일이 이렇게 나오는데, GitHub 로그인을 하면 저렇게 나오는게 의도된건가요? 🧐

**Comment by velopert** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 고쳐야겠네요 왜 제 이메일이 저기에...
