### ISSUE TITLE
글쓰기 삽입

### ISSUE THREAD

**Issue by YoungJInzz** [velopert/velog-client#32]
글쓰기중 중간에 문자를 삽입시 '삽입'이 아니라 '수정'으로 처리되서 뒤에 글씨가 

지워지면서 타이핑되네요.원래 그럤는지 기억이 잘 안나는데 버전업되면서 바뀐건가요 

아님 원래 그래왔던건가요?

**Comment by velopert** [comment]
한번 Insert 키를 눌러보시겠어요?

**Comment by YoungJInzz** [comment]
Insert키로 해결되었습니다.감사합니다.
