### ISSUE TITLE
시리즈명 중복문제

### ISSUE THREAD

**Issue by YoungJInzz** [velopert/velog-client#33]
시리즈추가시 흔한 시리즈명 ex)javascript,css등으로 설정 시 '존재하는  url입니다'라고 뜨네요

근데 시리즈에 들어가서 시리즈명수정시 javascript_alpha이런식으로 만들었던 시리즈명이 javascript로 바뀝니다.

시리즈명중복값처리가 전체사용자가 아니라 본인계정내에서만 중복안되면 되는거 아닌가요?

**Comment by velopert** [comment]
시리즈 설정 쪽에 로직에 좀 문제가 있군요!
서버 관련 이슈여서 서버쪽으로 이슈를 링크해놓고 여기 이슈는 닫겠습니다 :)
