### ISSUE TITLE
syntax highlighting 지원 언어를 확장했으면 합니다

### ISSUE THREAD

**Issue by BaekGeunYoung** [velopert/velog-client#34]
저는 프로그래밍 언어로 코틀린을 자주 사용하고, 인프라 관련 글을 올릴 때 yaml 형식의 코드를 많이 올리는 편인데요, syntax highlighting이 되지 않아서 글이 예쁘게 읽히지가 않는 것 같아요 ㅜㅜ 좀 더 다양한 언어에 대해 하이라이팅을 지원했으면 합니다.

**Comment by ilcm96** [comment]
Flutter 덕분에 가파르게 상승하고 있는 Dart도 지원해주시면 좋겠습니다

**Comment by velopert** [comment]
네! yaml, dart 오늘 저녁에 추가하겠습니다 :)
