### ISSUE TITLE
게시글을 삭제하지 않고 탈퇴했을 때 게시글이 검색됩니다.

### ISSUE THREAD

**Issue by lxodud** [velopert/velog-client#356]
https://velog.io/@xodud1998223/iOS-WWDC2020-Detect-Body-and-Hand-Pose-with-Vision-1
이 url인데 계속검색되네요 삭제가능할까요

**Comment by velopert** [comment]
GraphQL 캐시로 인한 문제로 바로 삭제처리가 되지 않았습니다.
문제가 가끔 있어서 캐시를 조만간 제거할 예정이에요.
