### ISSUE TITLE
헤더 우측 새글 작성 버튼 옆 유저 메뉴 이슈

### ISSUE THREAD

**Issue by WDever** [velopert/velog-client#37]
의도하신 바인지 모르겠지만 한번 클릭하여 유저 메뉴가 보여진 후 다시 유저 사진을 클릭하여도 메뉴가 접히지 않습니다. 꼭 다른 섹션을 클릭하여야 접힙니다.

![image](https://user-images.githubusercontent.com/37620133/74227365-acf0f500-4d01-11ea-87a3-60bf65875ebb.png)

**Comment by velopert** [comment]
고치겠습니당
