### ISSUE TITLE
글 작성 중에 임시저장되면 작성되는 위치가 최상단으로 강제로 이동되는 문제

### ISSUE THREAD

**Issue by WonHeeSoo** [velopert/velog-client#40]
글 작성 중에 임시저장되면 작성되는 위치가 최상단으로 강제로 이동되는 문제가 있습니다.

**Comment by velopert** [comment]
그렇군요! 한번 검토해보겠습니다.

**Comment by velopert** [comment]
사용하시는 브라우저가 어떻게 되시나요? 어떻게 해야 재현 할 수 있는지 설명 주시면 감사하겠습니다!

**Comment by WonHeeSoo** [comment]
문제가 생긴 브라우저는 크롬 웹에서 작성했습니다.
개인적으로 테스트해보니 글을 작성하다가 10초 정도 글을 쓰지 않으면 자동으로 `포스트가 임시저장되었습니다.`라는 문구가 뜨며 임시저장되는데 그때 강제로 작성되는 위치가 최상단으로 이동됩니다.

**Comment by velopert** [comment]
감사합니다. 사용하시는 운영체제는 어떻게 되세요?

**Comment by WonHeeSoo** [comment]
Window 10 64비트 입니다.

**Comment by velopert** [comment]
제가 직접 해볼땐 재현이 되지 않아서, 우선 자동 임시 저장을 할 때는 메시지를 띄우지 않도록 고쳐봤습니다.
(애초에, 너무 색상이 튀어서 글 쓰는데 방해가 될 것 같기도 해서요)

한번 똑같은 증상이 나타나는지 확인 부탁드립니다.
다시 나타나게 된다면, 다시 이슈 열어주세요.

아직 배포가 진행중이니 [배포](https://github.com/velopert/velog-client/runs/439132438?check_suite_focus=true) 가 끝나고 확인부탁드려요.

**Comment by HADMARINE** [comment]
포스트 저장 시에 커서가 올라가는 문제가 아직도 존재합니다..!
