### ISSUE TITLE
표 작성시 테두리 유무

### ISSUE THREAD

**Issue by raram2** [velopert/velog-client#41]
글에 대한 요약 정리로 표를 즐겨 사용하는데,
이번 업데이트로 확인해보니 표 테두리가 없어졌다는 것을 알게 됐습니다. 
개인적으로 행과 열의 구분이 쉽지 않아 가독성을 해친다고 생각합니다.
velopert님은 어떻게 생각하시는지 궁금합니다.

**Comment by velopert** [comment]
표 테두리를 넣어야 한다고 생각합니다 ^^ 수정하겠습니다.

**Comment by velopert** [comment]
수정됐습니다~
