### ISSUE TITLE
글, 시리즈, 소개 버튼 클릭시 console창 내역

### ISSUE THREAD

**Issue by kjungit** [velopert/velog-client#415]
![스크린샷 2023-04-11 오후 9 15 21](https://user-images.githubusercontent.com/100064540/231159479-73b0866f-32f1-42a4-a46e-73bd54a76c72.png)
![스크린샷 2023-04-11 오후 9 15 29](https://user-images.githubusercontent.com/100064540/231159501-5d84c7d3-7cba-4494-9e93-5a2c218aa5f6.png)

글, 시리즈, 소개 버튼 클릭시 console창에 문구가 계속 나오네요.

**Comment by winverse** [comment]
의견 주셔서 감사합니다 :)
