### ISSUE TITLE
포스트 에디터에서 사진을 포함한 채 글씨를 작성하면 깜빡이는 문제

### ISSUE THREAD

**Issue by HADMARINE** [velopert/velog-client#42]
<img width="1283" alt="Screen Shot 2020-02-12 at 1 01 26 AM" src="https://user-images.githubusercontent.com/46421618/74254013-340a9100-4d33-11ea-856e-b74ed9c171cc.png">

이런식으로 사진을 포함한 게시물을 작성하면 깜빡입니다.

**Comment by velopert** [comment]
사용하시는 브라우저가 Safari 가 맞으신가요?

**Comment by velopert** [comment]
Safari 에서 재현되는 것을 확인했습니다. 고쳐볼게요!

**Comment by HADMARINE** [comment]
> 사용하시는 브라우저가 Safari 가 맞으신가요?

넵 맞습니다!

**Comment by velopert** [comment]
해결 됐습니다 :)
