### ISSUE TITLE
비공개 게시물 전채공개 전환 불가 오류

### ISSUE THREAD

**Issue by jayarnim** [velopert/velog-client#427]
안녕하세요 벨로그 아이디 @jayarnim 을 사용하고 있는 유저입니다. 다름이 아니라 며칠 전부터 서포트 벡터 머신 관련 두 가지 게시물이 비공개에서 전체공개로 전환되지 않고 있어 트위터 쪽지 및 구글 메일로 연락드렸으나 미회신 중이셔서 이슈 남깁니다.

해당 게시물 주소는 다음과 같습니다.

http://velog.io/@jayarnim/결정-경계와-Support-Vector-Machine

http://velog.io/@jayarnim/번외-비선형-데이터-세트의-결정-경계-구하기

**Comment by velopert** [comment]
불편을 드려 죄송합니다.
공개처리 하였습니다.

최근 벨로그 담당 개발자를 채용하였고
스팸 필터 오류 부분도 우선순위를 높여 진행하도록 하겠습니다!

**Comment by jayarnim** [comment]
확인했습니다! 기술블로그로 여러 플랫폼을 고려하다가 지난 달부터 벨로그를 사용하고 있는데 단정한 디자인과 편리한 기능들 덕분에 큰 시간을 소요하지 않고 공부한 내용들 잘 정리하고 있습니다 :-) 좋은 플랫폼 만들어주셔서 감사드립니다~
