### ISSUE TITLE
태그 순서 정렬

### ISSUE THREAD

**Issue by ImSejin** [velopert/velog-client#435]
항상 노고에 감사드립니다.

---

## 문제점

![image](https://github.com/velopert/velog-client/assets/46176032/15b7697d-9c07-490a-8282-d7f4bf3c4cb6)

페이지에서 보여지는 태그들의 순서가 어떠한 규칙으로 나열되는지 모르겠습니다.
최근 수정일자 기준으로 정렬되는 것 같은데 맞을까요?

## 바라는 점

사용자가 태그 나열 순서를 설정할 수 있었으면 합니다.
아래는 여러 아이디어입니다.

* drag&drop으로 태그 간 순서를 개별적으로 설정
* 이름 순으로 정렬
* 설정 페이지에서 여러 정렬 방법 중 하나를 설정

**Comment by winverse** [comment]
Velog를 이용해주셔서 감사합니다.

현재 태그의 정렬 순서는 해당 태그로 작성된 글 개수 입니다.
바라는 점을 내부에서 의논해보도록 하겠습니다.

의견 주셔서 감사합니다!
