### ISSUE TITLE
별다른 내용을 적지 않더라도.. 자동 비공개 됩니다... 

### ISSUE THREAD

**Issue by 07LEE** [velopert/velog-client#439]
글을 수정하거나 작성하면 자동 비공개 되어버려서, 키워드 문제인가 싶어 이것 저것 게시해서 확인해보았는데,

![image](https://github.com/velopert/velog-client/assets/95900411/7357c409-fd4c-4625-ae7d-812d2a554b87)

별다른 내용 없이 작성하여도 비공개 처리가 되어버립니다.. 대체 뭐가 문제일까요

**Comment by FeelingXD** [comment]
다른분들도 똑같은 이슈가 지속적으로 발생하고있는것같습니다. 
글에 문제가 없으면 추후 자동으로 공개로 전환되는것같습니다.
