### ISSUE TITLE
닉네임과 댓글 이름 불일치

### ISSUE THREAD

**Issue by YoohaBae** [velopert/velog-client#442]
닉네임 변경 후 게시물 작성자의 유저 네임은 A라는 이름으로 나오는데 댓글을 달았을때 A라는 이름으로 달리는것이 아닌 velog.io/@`B의 B로 보입니다.
댓글달 때의 이름도 블로그 닉네임으로 보이게 할 수는 없을까요?

**Comment by winverse** [comment]
댓글, 포스트, 포스트 카드등 닉네임으로 변경 과정에 있습니다.

의견주셔서 감사합니다 :)
