### ISSUE TITLE
비공개 처리에 관하여

### ISSUE THREAD

**Issue by soo1e** [velopert/velog-client#443]
블록 VS 인라인 요소
블록(Block) 요소:

블록 요소는 항상 새로운 줄에서 시작하며 가능한 가득한 너비를 차지한다.
즉, 해당 요소 이전과 이후의 요소는 항상 새로운 줄에 표시된다.
width와 height 속성을 설정하여 가로와 세로 크기를 조정할 수 있다.
margin, padding, border 속성을 모두 사용할 수 있다.

예시

<div>, <p>, <h1>~<h6>, <ul>, <li>, <table>
인라인(Inline) 요소:

인라인 요소는 문장 내에서 흐름(flow)에 따라 나란히 위치한다.
즉, 해당 요소 이전과 이후의 내용과 같은 줄에 표시된다.
width와 height 속성을 설정하여 가로와 세로 크기를 변경할 수 없으며, 오로지 컨텐츠의 크기만큼 공간을 차지한다.
margin의 상하 값(top, bottom)과 width, height를 설정할 수 없고, padding과 border는 사용할 수 있다.

예시

<span>, <a>, <strong>, <em>, <img>, <button>
블록 요소는 주로 레이아웃과 구조를 만들 때 사용되며, 인라인 요소는 텍스트와 같은 내용의 작은 부분에 스타일을 적용하거나, 텍스트 중간에 링크나 강조 등의 요소를 삽입할 때 사용된다. 이러한 요소들을 적절하게 조합하여 웹페이지를 디자인하고 구조화하는 것이 중요하다.

마진 상쇄 ( Margin collapsing )
CSS의 특정 레이아웃 규칙에 의해 발생하며, 두 개 이상의 블록 요소가 수직으로 나란히 배치되어 있을 때 발생하는 경우가 일반적이다.
형제 블록 요소들 사이의 상하 마진이 만나면 더 큰 마진으로 상쇄된다. 예를 들어, 두 개의 div 요소가 수직으로 나란히 배치되어 있고, 두 요소 각각의 아래쪽 마진이 20px, 30px로 지정된 경우, 두 요소의 아래쪽 마진은 30px로 상쇄된다.

"box-shadow" 속성
박스 그림자는 테두리 주변에 그림자를 추가하는 속성이다.

box-shadow : 5px 5px 5px rgba(0, 0, 0, 0.2);
첫 번째 요소는 X축 오프셋이다.
그림자를 요소 바로 뒷부분에서 오른쪽으로 약간 이동하여 적용하는 값이다.

두 번째 요소는 Y축 오프셋이다.
이 값은 그림자를 약간 아래로 이동시켜준다.

세 번째 요소는 테두리 흐림을 설정하는 옵션이다.
테두리 흐림을 이용하면 항목의 테두리를 부드럽게 만들 수 있다.

네 번째 요소는 박스 그림자의 색상이다.

과제

이렇게 만들었던 기존의 페이지를

이렇게 바꿔보라는 과제를 받았다.

span 태그를 이용하여 날짜를 강조했다.
메인, 푸터를 이용해 html 요소를 재정비했다.
또한 메인 섹션의 css 값에 마진 오토와 너비 제한을 두었다.
메인 섹션 상단에 여백을 주기 위해 마진 탑을 줬고 나는 푸터 자체에 마진 탑을 줬지만 그것보다는 메인 섹션에 마진 바텀 값을 주는 것이 좀 더 정리하는 데 편할 것 같다. 이 점은 습관을 들여야겠다.
이미지에도 테두리를 줬다.
● 태그 유형 선택자

o CSS: p { ... }

o 예를 들어 이 HTML 요소를 선택하면:

<p>Some text...</p>
o 이 선택자는 이 태그 유형의 모든 HTML 요소를 선택합니다.

● 아이디 선택자

○ CSS: #some-id { ... }

○ 예를 들어 이 HTML 요소를 선택하면:

<h1 id="some-id">...</h1>
○ 이 선택자는 이 ID가 있는 요소를 선택합니다(페이지당 한 번만 가능)

● 클래스 선택자

○ CSS: .some-class { ... }

○ 예를 들어 이 HTML 요소를 선택하면:

<h1 class="some-class">...</h1>
○ 이 선택자는 이 클래스가 있는 모든 HTML 요소를 선택합니다.

● 속성 선택기(신규)

○ CSS: [src] { ... }

○ 예를 들어 이 HTML 요소를 선택하면:

<img src="...">
○ 이 선택자는 이 HTML 속성이 있는 모든 요소를 선택합니다.

● 범용 선택기(신규)

○ CSS: * { ... }

○ 예를 들어 이 HTML 요소를 선택하면:

<p>....</p><img ...>
○ 이 선택자는 모든 HTML 요소를 선택합니다(상속을 통하지 않고 모든 HTML 요소를 개별적으로 대상으로 지정하는 것처럼 직접 가능).

● 그룹화 선택자/선택자 리스트

○ CSS: p, .some-class { ... }

○ 예를 들어 이 HTML 요소를 선택하면:

<p>...</p><h2 class="some-class">...</h2>
○ 이 선택자는 해당 목록의 개별 선택자와 일치하는 모든 요소를 ​​선택합니다.

● 결합 선택자

○ CSS: p.some-class { ... }

○ 예를 들어 이 HTML 요소를 선택하면:

<p class="some-class">...</p>
○ 이 선택자는 두 조건을 모두 충족하는 모든 요소를 ​​선택합니다(예: 이 예제에서는 "some-class" 클래스가 있는 "

" 요소).

● 의사 선택자

○ CSS: a:hover { ... }

○ 예를 들어 이 HTML 요소를 선택하면:

<a>...</a>
(사용자가 해당 요소 위로 마우스를 가져갈 때)

○ 이 선택기는 이 "의사 상태"를 충족하는 모든 요소를 ​​선택합니다(즉, 이 예에서 가리키고 있는 모든 링크).

이 글인데 자꾸 비공개처리가 되네요 
https://velog.io/@soo1e/DAY-8 
비공개된 링크인데 당연하게도 아무것도 안 뜨네용

**Comment by wonjinYi** [comment]
혹시 https:// 나 링크가 본문에 있나요? 저는 지금 이 문제 때문에 비공개처리되네요.
