### ISSUE TITLE
404가 너무 뜹니다.. 

### ISSUE THREAD

**Issue by TodayOneStep** [velopert/velog-client#445]
안녕하세요. 

정확한 원인은 모르겠지만 제 아이디로 로그인해서 velog를 사용하면서 404가 너무 많이 뜹니다. 어쩌다 한번 뜨는 것이 아닌 10번 쓰면 6번 정도 뜨는 것 같고, 리프레시해서 다시 404가 안뜨게 할 수 있는 방법도 모르겠습니다. 원인도 잘 모르겠습니다만 제 추측으로는 왼쪽에 태그를 누르고 포스팅을 누르면 404가 뜨는 거 아닌가 싶습니다.. 

![image](https://github.com/velopert/velog-client/assets/140144634/38a868bb-cfb7-4f0a-ad95-8813a866b6b9)

**Comment by TodayOneStep** [comment]
이 상황에만 뜨는 것도 아닌 것 같습니다.. 솔직히 404가 너무 떠서 서비스 이용 자체가 불가능할 정도입니다. 새로고침하면 풀린다던가 어떤 리프레시 방법이라도 있어야 할텐데 그것도 파악하기 어렵고요,, 저만 그런 것인지 왜 관련 문의가 없는지 모르겠지만 심각한 상황인데 어떡해야 할까요?

**Comment by TodayOneStep** [comment]
아 그리고 포스팅 보다가 왼쪽 상단 눌러서 제 벨로그 목록으로 나가면 화면이 안뜰때도 많이 발생합니다. 
![image](https://github.com/velopert/velog-client/assets/140144634/1c6f7311-1466-4ec8-a762-e7e22b016468)

**Comment by hj4645** [comment]
안녕하세요 TodayOneStep님! 
저도 같은 문제를 겪고 있어 이슈 남기고 갑니다. (동일한 상황에서 나타나는 이슈 같아 새롭게 이슈 작성하지 않고 코멘트로 남깁니다~)

우선 저도 404 에러 문제로 게시글 확인에 어려움을 겪고 있습니다.
이에 언제 404 오류가 발생하는지 궁금해 몇가지 경우를 테스트 해보았습니다.

[게시글 조회 성공⭕ 케이스]
1. Velog 접속 후 다른 페이지 이동 없이 바로 `내 벨로그`로 이동해 `태그목록-전체보기`가 선택된 상황에서 조회를 원하는 게시글 클릭 시 조회 성공
2. `내 벨로그`로 이동해 `시리즈`가 선택된 상황에서 조회를 원하는 게시글 클릭 시 조회 성공
3. `내 벨로그`로 이동해 조회를 원하는 게시글 `키워드 검색` 후 클릭 시 조회 성공

👉 `전체보기, 시리즈, 검색 기능`은 **_정상 작동_** 하는 것 같습니다.

[게시글 조회 실패❌ 케이스]
1. Velog 접속 후 다른 페이지 이동 없이 바로 `내 벨로그`로 이동해 `태그목록-조회를 원하는 태그`가 선택된 상황에서 게시글 클릭 시 조회 실패
- 새로고침 후 조회 시도 실패
- 뒤로가기 후 조회 시도 실패
- 해당 태그로 연결되는 URL 복사 붙여넣기 후 조회 시도 실패

👉 `태그 기능`이 **_비정상 작동_** 하는 것 같습니다.

### 실패하는 경우 파라미터 값이 모두 `null`로 넘어옵니다.
ex) https://velog.io/@아이디/null

로그인/로그아웃 한 경우 모두 위에서 기술한 것과 동일하게 작동했습니다...
태그 검색 기능을 자주 이용하고 있던지라 얼른 고쳐지면 좋겠네요ㅠㅠ...

**Comment by TodayOneStep** [comment]
안녕하세요. hj4645님

이슈 남겨주신 댓글 보고, 많이 배우고 갑니다. 감사합니다.

**Comment by velopert** [comment]
고쳐졌습니다.
태그로 게시글 조회 쿼리가 느려서 최적화를 하는 과정에서 url 주소 부분을 반환을 안해서 이러한 오류가 발생했네요
불편을 드려 죄송합니다.

이제 정상적으로보입니다.

**Comment by TodayOneStep** [comment]
안녕하세요. velopert님 이슈 해결해주셔서 감사합니다!
