### ISSUE TITLE
포스트 수정 / 생성할 때 URL 설정 시 빈칸이면 자동으로 URL을 채워주는 기능

### ISSUE THREAD

**Issue by HADMARINE** [velopert/velog-client#45]
<img width="965" alt="Screen Shot 2020-02-12 at 1 08 27 AM" src="https://user-images.githubusercontent.com/46421618/74254727-2f92a800-4d34-11ea-9e2c-5ec09f3ef2b8.png">

기능 자체는 좋은데, 빈칸으로 만들어 놓고 링크를 작성할 때 빈칸이 허용되지 않고 자동으로 URL이 채워져서 조금 불편한것 같습니다. placeholder로 기본 url을 제공하였으면 좋겠네요

**Comment by velopert** [comment]
참! 이건 버그입니다. 고칠게요 :)
