### ISSUE TITLE
비공개 글 필터링 키워드 제보

### ISSUE THREAD

**Issue by Kwon770** [velopert/velog-client#456]
"AWS S3를 통한 사진 업로드와 AI 리뷰 분석 모델을 통한 리뷰 분석 요청이라는 2개의 외부 서비스를 거친 후 리뷰 데이터가 DB에 저장됩니다."

라는 문장에서 "후 리" 부분 때문에 검열됩니다.

어느 부분 때문에 비공개되는지 헤매는 분들을 위해서도 이슈에 등록합니다.

**Comment by aggie97** [comment]
감사합니다 덕분에 공개 처리할 수 있었습니다 👍🏼
