### ISSUE TITLE
작성글 통계 페이지 데이터 미출력 오류

### ISSUE THREAD

**Issue by Joonkkyo** [velopert/velog-client#459]
원래 통계 항목에서 일일 조회수 히스토리를 그래프 형식으로 볼 수 있었는데,
현재 다음과 같이 오늘, 어제 조회수가 0으로 출력되고 이전 그래프도 표시가 되지 않는 현상이 발생합니다.
(chrome, edge 브라우저에서 모두 동일하게 발생)

![image](https://github.com/velopert/velog-client/assets/12121282/7c6d278d-b3dc-4f57-8a71-97bf3c9a9611)

**Comment by ojj1123** [comment]
@Joonkkyo 이 이슈 닫으신 이유가 있나요? 저도 동일한 문제가 생겨서요.

**Comment by Joonkkyo** [comment]
https://velog.io/@velog/post-stats-update
해당 링크를 보니 성능 이슈로 통계 기능을 잠시 비활성화한다고 공지하셨었더라구요.
조만간 개선된 기능 도입 예정이라고 하신 것 확인해서 이슈 닫아놓았습니다.
