### ISSUE TITLE
GitHub 소셜 로그인 오류

### ISSUE THREAD

**Issue by JiHongKim98** [velopert/velog-client#468]
![gif](https://github.com/velopert/velog-client/assets/144337839/45ba0597-5055-4335-bf08-10b5b15cf2e4)

리다이렉션
https://v2cdn.velog.io/api/v2/auth/social/redirect/github?next=&isIntegrate=0

오류 코드
{"errors":[{"message":"404: Not found. Only \"/\", \"/graphql\", and \"/log\" is allowed."}]}

GitHub 소셜 로그인시 로그인이 안되고 "https://v2cdn.velog.io/api/v2/auth/social/redirect/github?next=&isIntegrate=0" 으로 리다이렉션되고 있습니다!

**Comment by hyungjungson** [comment]
저도 같은 현상입니다.

**Comment by hwinkr** [comment]
저도 같은 오류로 로그인이 안되네요..

**Comment by velopert** [comment]
고쳐졌습니다. 감사합니다.
