### ISSUE TITLE
XSS 공격 취약점 발견

### ISSUE THREAD

**Issue by Ubinquitous** [velopert/velog-client#469]
글 내용이나 댓글에서 svg태그와 onload를 함께 사용하면 script태그가 실행되는 취약점이 발생합니다.

![velog_xss3](https://github.com/velopert/velog-client/assets/102154880/2774a429-7201-4caf-aa2b-1f6b4498ba65)

https://github.com/velopert/velog-client/assets/102154880/015a59da-50df-446b-a3f4-58154bccbe29

https://github.com/velopert/velog-client/assets/102154880/d5ce8c3c-cc29-4087-964e-945365e4d9f1

**Comment by velopert** [comment]
제보 감사합니다. 고치겠습니다 !

**Comment by Ubinquitous** [comment]
확인해주셔서 감사합니다! 바쁘실테지만 밑의 PR도 괜찮으시다면 한번 확인 부탁드리겠습니다!
https://github.com/velopert/velog-client/pull/470
