### ISSUE TITLE
글을 작성할 때 마지막 임시저장 시간으로 생성시간이 잡히는 오류가 있습니다.

### ISSUE THREAD

**Issue by HADMARINE** [velopert/velog-client#47]
오늘 두 게시물을 작성하였는데, 생성 즉시 확인한 시간이 30분, 40분 이 지난 것으로 기록되어 있네요

**Comment by velopert** [comment]
서버 이슈로 확인되어 이슈 링크하고 여기 이슈는 닫겠습니다 :)
