### ISSUE TITLE
자동 비공개 키워드 '향후' 제보합니다.

### ISSUE THREAD

**Issue by pp8817** [velopert/velog-client#474]
안녕하세요!
게시물 등록 중 자동으로 비공개처리가 되길래 한줄 한줄 찾아보니
'**향후** 리포지토리를 JDBC 기술이 아닌 다른 기술로 변경한다면, 그래서 SQLException이 아니라 예를 들어서 JPAException으로 예외가 변경된다면 어떻게 될까?'
라는 문장에서 '향후'라는 단어가 스팸으로 비공개 처리됩니다.
비공개 처리되는 이슈에서 참고부탁드립니다!

**Comment by do0ori** [comment]
안녕하세요.
velog 게시물 작성 중 게시물이 계속 자동 비공개 처리가 되는 일이 있어 해결하던 중 본문을 한 줄씩 지워가며 확인해보니 "후 리", "후리"라는 단어 때문임을 확인하였습니다. (공백은 무시되는 것 같습니다.)
저는 게시글 본문에서 "이 key는 추**후 리**액트가..."와 같이 사용했었는데요,
@pp8817 님 문장에서도 "향**후 리**포지토리..."에서 "후 리"가 문제가 된 것으로 보여집니다.
따로 포스트를 만들어 본문에 "후 리" 또는 "후리"만을 입력해본 결과 자동 비공개 처리가 되는 것을 확인했습니다.
참고 부탁드립니다. 감사합니다.

**Comment by pp8817** [comment]
> 안녕하세요. velog 게시물 작성 중 게시물이 계속 자동 비공개 처리가 되는 일이 있어 해결하던 중 본문을 한 줄씩 지워가며 확인해보니 "후 리", "후리"라는 단어 때문임을 확인하였습니다. (공백은 무시되는 것 같습니다.) 저는 게시글 본문에서 "이 key는 추**후 리**액트가..."와 같이 사용했었는데요, @pp8817 님 문장에서도 "향**후 리**포지토리..."에서 "후 리"가 문제가 된 것으로 보여집니다. 따로 포스트를 만들어 본문에 "후 리" 또는 "후리"만을 입력해본 결과 자동 비공개 처리가 되는 것을 확인했습니다. 참고 부탁드립니다. 감사합니다.

좋은 정보 감사합니다!
