### ISSUE TITLE
velog 출판하기 버그

### ISSUE THREAD

**Issue by Yangseungchan** [velopert/velog-client#476]
<img width="838" alt="image" src="https://github.com/velopert/velog-client/assets/38908080/e2a2899c-24fc-4b23-894f-058b0034d9ec">

<img width="838" alt="image" src="https://github.com/velopert/velog-client/assets/38908080/92bc1c64-9271-4592-b03c-2b4759cedbc3">

글의 내용에 따라(?) 위의 에러로 인해서 출판하기를 할 수 없습니다.

간혹 극적으로 출판이 통과하는 경우도 있어 혼란스럽습니다.

**Comment by dodok8** [comment]
`post.ts`의 626 줄에 오류가 있네요.
