### ISSUE TITLE
한번 글을 등록하고 나서 수정하기를 시도하면 먹통이 됩니다.

### ISSUE THREAD

**Issue by devToroko** [velopert/velog-client#478]
제가 github 계정을 연동해서 velog 를 사용중입니다.
그런데 어제부터인가 이상하게 글을 수정하려고 하면 먹통이 됩니다.

그냥 아무 말이나 쓴 게시물을 한번 생성하고,
수정하기를 시도해도 결과는 마찬가지입니다.

에러 로그는 이렇게 나오더군요.

![msedge_gIyJvHqTT0](https://github.com/velopert/velog-client/assets/51431766/d7d05246-4121-4dd5-8e3d-4092523f4e92)

![msedge_Ob9RZyVOcA](https://github.com/velopert/velog-client/assets/51431766/04fac6a3-521a-4005-bd6c-be22fb4bc323)

**Comment by dodok8** [comment]
#476 이랑 중복같네요

**Comment by devToroko** [comment]
오늘 다시 해보니 또 정상 동작을 하네요... 
해결이 된 거 같으니 Close 하도록 하겠습니다.
