### ISSUE TITLE
출판하기 및 수정하기 오류

### ISSUE THREAD

**Issue by dangdangs0** [velopert/velog-client#479]
사진이 있을 때, 출판하기 및 수정하기가 되지 않습니다.

또한 출판 후, 사진 유무와 관계없이 수정이 되지 않는 것 같습니다!

![image](https://github.com/velopert/velog-client/assets/52357071/bebefbc6-7416-45fe-9c6d-c682bb49d35a)

**Comment by dodok8** [comment]
#476 과 도일 문제 같습니다

**Comment by winverse** [comment]
혼란을 드려 죄송합니다. 처리 되었습니다.
