### ISSUE TITLE
벨로그 제목(username.log)에 웹폰트가 적용되지 않음

### ISSUE THREAD

**Issue by ilcm96** [velopert/velog-client#48]
## Env
- Windows 10
- Chrome 80

---

![nowebfont](https://user-images.githubusercontent.com/20370957/74258092-1b04de80-4d39-11ea-8270-d06df769cc2f.PNG)
기본값이 username.log인 벨로그 제목 부분에 웹폰트가 적용되지 않습니다.

**Comment by velopert** [comment]
아이쿠, Spoqa Han Sans 를 없애는 과정에서 Fira Code 가 함께 날라갔었군요!
