### ISSUE TITLE
velog 작성글이 전부 날라갔습니다.

### ISSUE THREAD

**Issue by Yeji-Yoon** [velopert/velog-client#480]
현재 상황
1. 12.29일날 수정하기 버튼 이 안 먹었어요.
2. 오늘 로그인을 하기위해 메일을 입력했는데
3. 제 메일로 회원가입 하기 메일이 오더라구요
4. 뭔지 몰라서 회원가입을 했는데 원래 제가 작성한 글이 전부 사라져서요.

문의사항
1. 제가 작성한 글 복구가 될까요?

**Comment by velopert** [comment]
안녕하세요, 스팸 게시글 삭제 과정에서 계정에 문제가 발생한 것 같습니다.
포스트는 백업을 하고 있어서 복구를 할 수 있습니다.
기존에 사용하시던 계정명을 알 수 있을까요? velog.io/@velopert 이런식으로 주소의 @뒤에 오는 값입니다.

**Comment by Yeji-Yoon** [comment]
-----Original Message-----

**Comment by Yeji-Yoon** [comment]
-----Original Message-----

**Comment by Yeji-Yoon** [comment]
안녕하세요.
혹시 언제 복구가 가능한지 알 수 있을까요?

**Comment by velopert** [comment]
yo***ye***2@naver.com 이메일로 만든 계정에 포스트들이 복구가 되어있습니다.

저희가 처음엔 스팸처리과정에서 문제가 발생했다고 생각했는데 계정을 조사해본결과 스팸 처리때문에 문제가 발생한 것은 아니였습니다 (가입한지 20일 이내에 스팸 게시글을 공개글로 올렸을때 해당 계정을 조사후 삭제합니다) 하지만 yoonyeji12 계정의 경우 가입한지 여러달되었고 글들을 모두 비공개글로 올렸기 때문에 저희 스팸 필터에 걸린것은 아닙니다.

저희가 보기엔 사용자측에서 탈퇴처리가 되었던것 같습니다. 일부 포스트는 복구되었고 일부 포스트는 부분적으로만 복구되었습니다. 불편을 드려 죄송합니다.

그리고 계정에 대하여 말씀주신 부분에 대해서 github 에서 이메일 부분을 자동으로 필터링 해서
```
제가 원래 사용하던 ***@***.*** 계정이 오류가 나서  ***@***.*** 도 만들었는데
***@***.*** 계정의 게시물 80개 있던 상태로 돌아가면 감사합니다.
```

이런 형태로 왔습니다.

yo***ye***2@naver.com 계정이 로그인이 안된다면 다른 계정에서 대해서 contact@velog.io 로 알려주세요.

**Comment by Yeji-Yoon** [comment]
신경 써주셔서 감사합니다.
저는 계정을 따로 삭제 한 기억이 없는데 왜 전부 날라갔을지 의문이네요..
게시물이 복구가 되었다고 했는데 몇개의 글은 아예 내용이 없고 복구된 글도 글의 앞부분만 복구 되었는데 
혹시 더이상 되지는 않는거죠?
