### ISSUE TITLE
게시글이 자동으로 비공개 처리 되고 있습니다!

### ISSUE THREAD

**Issue by hrJin9** [velopert/velog-client#482]
안녕하세요! 벨로그 이용한지 한 3개월 차인데요,

최근에 작성한 글 중에 자동으로 비공개처리가 되어서 전체공개가 되지 않는 글이 있어서 제보합니다.
https://velog.io/@bushyerin/3.-Security-JWT-%EC%A0%81%EC%9A%A9-2

또 , A 계정으로 로그인 했다가 다시 B계정으로 로그인했을때, B 계정으로 글을 쓰면 글 작성이 안되더라구요.
개발자 도구를 열어보니 내 포스트가 아니라는데... 브라우저를 껐다 키고 쿠키를 삭제해봐도 마찬가지였습니다. 현재 로그인된 사용자는 B임을 확인했구요!
이부분 오류도 수정해주시면 감사하겠습니다ㅠㅠ

**Comment by winverse** [comment]
안녕하세요.

이용에 불편을 드려서 죄송합니다.

1. 해당 게시글은 전체공개로 변경 되었습니다.
2. 여전히 같은 문제가 발생하고 계시다면 번거로우시겠지만 글 작성시 발생하는 에러 메시지를 알려주시면 감사하겠습니다.

감사합니다 :)
