### ISSUE TITLE
비공개에서 공개 전환 오류

### ISSUE THREAD

**Issue by kimsooin77** [velopert/velog-client#483]
안녕하세요 react-query 관련 게시물을 비공개에서 공개로 전환했는데 반영이 되지 않는 문제가 발생하고 있습니다. 혹시 문제가 되는 키워드가 포함되어 있을까요? 확인 부탁드립니다. https://velog.io/@ssooo_kk_77/React-Query%EB%9E%80

**Comment by winverse** [comment]
안녕하세요 불편을 드려서 죄송합니다.

해당 게시글은 공개 게시글로 보여지는데 어떤 문제가 있을까요?

**Comment by kimsooin77** [comment]
해당 이슈는 원인이 되는 키워드를 찾아서 수정했더니 공개로 전환이 되어 해결했습니다! 그런데 포스팅한 글 중 algorithm 태그로 등록한 글들은 전체 목록에서는 잘 보이지만 왼쪽 태그 목록에서 algorithm 태그를 선택하면 "포스터가 없습니다"라고 뜨는데 왜 그런걸까요? 이 부분만 다시 확인 부탁드립니다. https://velog.io/@ssooo_kk_77/posts?tag=algorithm
