### ISSUE TITLE
태그 누락 이슈

### ISSUE THREAD

**Issue by kimsooin77** [velopert/velog-client#487]
포스팅한 글 중 algorithm 태그로 등록한 글들은 전체 목록에서는 잘 보이지만 왼쪽 태그 목록에서 algorithm 태그를 선택하면 "포스터가 없습니다"라고 뜨는데 왜 그런걸까요?  확인 부탁드립니다. https://velog.io/@ssooo_kk_77/posts?tag=algorithm

**Comment by winverse** [comment]
불편을 드려 죄송합니다!
해당이슈는 https://github.com/velog-io/velog/commit/20be37d232fc878ca3351b341911fbf56e259b53 에서 처리 되었습니다.
감사합니다 :)
