### ISSUE TITLE
글 작성 페이지 접근시 404페이지가 보인 뒤 작성 화면으로 이동되는 문제

### ISSUE THREAD

**Issue by kshired** [velopert/velog-client#489]
안녕하세요 velog를 개발 블로그로 잘 쓰고 있습니다.

현재 velog에서 글을 작성하기 위해 작성 페이지에 접근시 404페이지가 보인 뒤 작성 화면으로 이동되는 문제가 있습니다.

실제로 404에서 멈추는 상황이 아니여서 글 작성에는 영향이 없지만 이슈인 것 같아 제보합니다.

## 문제 상황

글 작성 화면 접근시 404 화면이 잠깐 렌더링된 후 작성화면으로 이동 됨.

## 재현 방식

로그인 후 https://velog.io/write 접근.

**Comment by winverse** [comment]
제보해주셔서 감사합니다 :)

해당 버그는 인식하고 있으며 차후 업데이트에 반영될 예정입니다.
