### ISSUE TITLE
포스트를 작성하고 있을 때, 자동저장때문에 커서가 자꾸 최상단으로 이동합니다.

### ISSUE THREAD

**Issue by HADMARINE** [velopert/velog-client#49]
커서가 최상단으로 이동하지 않게 수정하거나, 자동저장을 트리거하는 방법을 바꾸면 좋을 것 같아요.
감사합니다:)

**Comment by velopert** [comment]
#40 이랑 비슷한 이슈 같은데 자동저장시 메시지 안띄우는 방식으로 수정을 했습니다.
한번 새로고침 해보시고 동일한 이슈 발생하는지 확인 부탁드립니다.
감사합니다.

**Comment by HADMARINE** [comment]
해결된 것 같습니다!
