### ISSUE TITLE
"진행 후 리" 자동 키워드 검열

### ISSUE THREAD

**Issue by dlalstlr12** [velopert/velog-client#492]
"진행 후 리팩토링"이라고 작성했더니 자동 검열로 비공개로 전환되더라구요 그래서 "진행하고 리팩토링"으로 수정했더니 공개로 전환되라구요

**Comment by winverse** [comment]
불편을 드려 죄송합니다.
해당 기능은 업데이트 예정입니다. 감사합니다 :)
