### ISSUE TITLE
벨로그 글을 공유시 해당 글에 대한 메타데이터가 표시되지 않습니다.

### ISSUE THREAD

**Issue by Daco2020** [velopert/velog-client#497]
벨로그 글을 공유하면 보통 해당 글에 대한 메타데이터를 바탕으로 미리보기가 표시되어야 하는데 벨로그 홈페이지만 표시되네요. 글 전달에 어려움이 있어 수정 부탁드리겠습니다. 🙏

![벨로그이슈](https://github.com/velopert/velog-client/assets/76890895/b930b728-c66d-4dd3-ad91-ede083fa8cc3)

**Comment by winverse** [comment]
안녕하세요. 혹시 여전히 같은 문제를 겪고 계실까요?

<img width="335" alt="스크린샷 2024-02-26 오전 10 10 00" src="https://github.com/velopert/velog-client/assets/40335396/55384cc2-316e-41ba-a434-4944e76b804d">
<img width="318" alt="스크린샷 2024-02-26 오전 10 10 30" src="https://github.com/velopert/velog-client/assets/40335396/03d6f781-2256-4217-8a6a-640e702c134a">

카카오 뿐 아니라 Slack, Discord 모두 잘 나오는 것으로 확인되고 있습니다.
향후 지속적으로 업데이트하여 SEO를 더욱 신경써 문제가 없도록 하겠습니다. 
Velog를 이용해주셔서 감사합니다 :)

**Comment by Daco2020** [comment]
해결 되었습니다! 답변 감사합니다! 🙏🏼
