### ISSUE TITLE
자동 비공개 처리 되고 있습니다.

### ISSUE THREAD

**Issue by milgun** [velopert/velog-client#498]
https://velog.io/@milgun/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-%EA%B8%B0%EC%B4%88-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0

해당 글을 '전체 공개'로 변경해도 자동으로 비공개 처리 되고 있습니다.

어떤 이유에서 비공개 처리 되는지 안내 부탁드립니다.

감사합니다.

**Comment by winverse** [comment]
불편을 드려 죄송합니다. 

해당글은 전체 공개로 변경되었습니다. 
감사합니다 :)
