### ISSUE TITLE
mathJax 기능

### ISSUE THREAD

**Issue by velopert** [velopert/velog-client#5]
https://github.com/velopert/velog/issues/89

**Comment by NaLDo627** [comment]
프론트엔드 초보자이지만, CDN 활용하면 간단히 구현되지 않을까 싶어서 글 남겨봅니다.
아래와 같이 html 파일 작성했을 경우 로컬에서도 작동되네요 ;)
```html
<!DOCTYPE html>
<html>
<head>
<title>MathJax TeX Test Page</title>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
</script>
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-MML-AM_CHTML">
</script>
</head>
<body>
When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$
</body>
</html>
```
저도 관련 이슈 넣으려다가 이미 있는것을 보고, 코멘트 남깁니다!

**Comment by ialy1595** [comment]
https://ialy1595.github.io/post/blog-construct-2/#mathjax
저도 비슷하게 마크다운 형식으로 글 쓰는 플랫폼에서 수식 기능을 넣는 작업을 해본 적이 있어서 공유해봅니다!

**Comment by velopert** [comment]
@NaLDo627 @ialy1595 
다들 도움 주셔서 감사합니다. :) 도움 주신 것들을 토대로 오늘 Mathjax 를 도입하려고 했었는데...
이를 사용하여 구현 할 시 포스트 에디터에서 미리보기로 실시간으로 확인해가면서 구현하는게 불가능해져서 (가능하긴 하겠지만 엄청난 삽질을 필요로 함)

다른 대안인 KaTeX 를 사용하기로 했습니다. 다행히, KaTeX 는 현재 벨로그에서 사용중인 remark 플러그인이 있어서 금방 도입 가능하더라구요!

**Comment by velopert** [comment]
@lee-zion, @jwon0615, @nck2, @NaLDo627, @ialy1595 님!

오늘 벨로그에 수식 입력 기능이 지원됐어요!

https://velog.io/@velog/katex-and-embed-support
