### ISSUE TITLE
게시글 수정 후 출간하려고 하면 반응형 스타일이 적용되지 않습니다

### ISSUE THREAD

**Issue by cadenzah** [velopert/velog-client#50]
<img width="583" alt="스크린샷 2020-02-12 오전 8 54 44" src="https://user-images.githubusercontent.com/18698124/74290571-9dab8f00-4d75-11ea-9f42-c893a8eea173.png">

새 개시글 작성시에는 잘 작동하더군요.

사용 환경은 Mac OS X이며, 동일한 증상을 Safari와 Chrome에서 확인했습니다.

**Comment by velopert** [comment]
아마, 새 게시글 작성 할 때도 안될겁니다.
아직까지는 글쓰기를 모바일 환경에서 하는 것을 고려하고 있지 않아서 반응형 디자인을 덜 구현하고 있었는데 생각해보니 데스크탑의 작은 창에서 쓰게 될 일도 있겠군요.

시간나는대로 구현해보겠습니다 :)

**Comment by velopert** [comment]
#123
