### ISSUE TITLE
게시물 공개 처리 부탁드립니다!

### ISSUE THREAD

**Issue by yminjuu** [velopert/velog-client#500]
https://velog.io/@ymj7250/React-API-%ED%98%B8%EC%B6%9C%EA%B3%BC-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B0%80%EA%B3%B5

어떤 키워드 때문인진 모르겠으나 자꾸 비공개 처리되고 있습니다.

**Comment by winverse** [comment]
불편을 드려 죄송합니다.
해당 게시물은 공개 처리 되었습니다. 

좋은 하루 보내세요 :)
