### ISSUE TITLE
비공개 게시물이 공개로 변환이 안 됩니다.

### ISSUE THREAD

**Issue by HyeoungGeun** [velopert/velog-client#505]
해당 블로그: https://velog.io/@gudrmsglgl/Github%EC%9C%BC%EB%A1%9C-%ED%98%91%EC%97%85

공개로 상태 변경 부탁드립니다.

**Comment by winverse** [comment]
안녕하세요. Velog를 이용해주셔서 감사합니다.

해당 게시글은 공개 상태로 보여집니다.

**Comment by HyeoungGeun** [comment]
@winverse 밑에 이슈를 참고하여 
글 내용을 수정해서 공개처리로 변경 됐습니다.
