### ISSUE TITLE
갑자기 모든 글이 비공개로 바뀌었습니다.

### ISSUE THREAD

**Issue by ScrapeStormkr** [velopert/velog-client#506]
공개상태로 변경 부탁드립니다.
velog 주소: [https://velog.io/@scrapestorm_kr/posts](https://velog.io/@scrapestorm_kr/posts)

**Comment by ScrapeStormkr** [comment]
> 공개상태로 변경 부탁드립니다. velog 주소: https://velog.io/@scrapestorm_kr/posts

**Comment by winverse** [comment]
안녕하세요.
해당 아이디는 광고글 작성에 따라서 게시글 공개가 제한 되어 있습니다.

광고성으로 여겨지는 게시글 수는 2024년 1월에 17건 이며 2024년 2월부터 18일까지 6건 입니다.

본사와 협의 되지 않은채 홍보성 글을 작성하는 것을 제한하고 있으니 이점 양해부탁드리겠습니다.
감사합니다.

**Comment by ScrapeStormkr** [comment]
안녕하세요.
먼저 협의없이 홍보성 글을 올려서 심심한 사과의 말씀드립니다.
서비스 이용약관에 홍보관련 항목이 없다고 판단한거 같습니다.
제한을 풀려면 어떻게 해야하는지, 협의 과정은 어떻게 이루어 지는지 궁금합니다.

2024년 2월 18일 (일) 오후 9:13, SangHyun Jang ***@***.***>님이 작성:

**Comment by ScrapeStormkr** [comment]
안녕하세요.
먼저 협의없이 홍보성 글을 올려서 심심한 사과의 말씀드립니다.
서비스 이용약관에 홍보관련 항목이 없다고 판단한거 같습니다.
제한을 풀려면 어떻게 해야하는지, 협의 과정은 어떻게 이루어 지는지 궁금합니다.
