### ISSUE TITLE
비공개 게시물 공개 처리 부탁드립니다!

### ISSUE THREAD

**Issue by LeeQuiett** [velopert/velog-client#507]
https://velog.io/@leequiett/%EC%A6%9D%EA%B0%90%EC%97%B0%EC%82%B0%EC%9E%90%EC%9D%98-%EC%86%8D%EB%8F%84%EC%B0%A8%EC%9D%B4

위 게시물입니다. 증감연산자에 관한 내용입니다. 감사합니다.

**Comment by winverse** [comment]
Velog를 이용해주셔서 감사합니다.

해당 게시글은 공개처리 되었습니다. :)
