### ISSUE TITLE
강제 비공개 전환이 되나 이유를 찾지 못하겠습니다

### ISSUE THREAD

**Issue by gyangtto** [velopert/velog-client#508]
https://velog.io/@g_tto_/JS-part-3.-%EB%B0%B0%EC%97%B4-Array
링크 확인 후 어떤 사유로 강제 비공개 전환처리가 되는지 확인 부탁드립니다.ㅠㅠ

**Comment by winverse** [comment]
불편을 드려 죄송합니다.

해당 게시글은 공개로 전환되었습니다.
Velog를 이용해주셔서 감사합니다 :)
