### ISSUE TITLE
게시글 비공개

### ISSUE THREAD

**Issue by jhkwag970** [velopert/velog-client#512]
안녕하세요!

글이 계속 자동 비공개가 되어서 이슈 남깁니다.

아이디는 @ddjam

게시글은 High Definition Map Overview 입니다.

url: https://velog.io/@ddjam/High-Definition-Map-Overview

**Comment by winverse** [comment]
안녕하세요 Velog를 이용중에 불편을 드려서 죄송합니다.

해당 게시글은 공개로 전환되었습니다.
감사합니다 :)
