### ISSUE TITLE
게시글 자동 비공개

### ISSUE THREAD

**Issue by gda05024** [velopert/velog-client#514]
게시글 자동 비공개 처리 문의드립니다.
어떤 키워드 때문에 자동 비공개 되는지 모르겠네요 ㅠ

아이디 : @gda05024
게시글 : 주니어 개발자 회고 그리고 이직
URL : https://velog.io/@gda05024/%EC%A3%BC%EB%8B%88%EC%96%B4-%EA%B0%9C%EB%B0%9C%EC%9E%90-%ED%9A%8C%EA%B3%A0-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EC%9D%B4%EC%A7%81

처리 부탁드립니다 ㅎㅎ 감사합니다!! :)

**Comment by gda05024** [comment]
"후 리"를 지우니깐 공개전환 되었습니다. 감사합니다.

**Comment by giibeom** [comment]
@gda05024 덕분에 저도 해결됐습니다 감사합니다! 🙇‍♂️

@winverse 
금지 키워드 같은 기능이 새로 생겼나 보군요 😅
금지 키워드가 있으면 강제로 비공개 처리하는것보다는 차라리 팝업 창이라도 띄워주고 저장이 안되게 구현되는게 좋지 않을까 싶습니다! 😂

**Comment by winverse** [comment]
@giibeom 좋은 의견 감사합니다.

게시글 자동 비공개 기능은 로직 수정, 키워드 정리 등과 같은 방식으로 현재 개선 중에 있습니다.
좋은 의견인 만큼 반영할 수 있도록 노력하겠습니다. 

감사합니다 :)
