### ISSUE TITLE
임시 저장 글 사라짐....

### ISSUE THREAD

**Issue by EunoChoi** [velopert/velog-client#519]
안녕하세요. 임시 저장 글 문의 드립니다.

임시 저장 글이 갑자기 사라지고 임시 글 목록에도 존재하지 않는데 복구 가능할까요..?
오늘 하루종일 작성한 게시글인데 사라져서 마음이 아픕니다... ㅠㅠ 

@eunocode
조각조각ing - 호이스팅, 실행컨텍스트, 스코프, this, 바인딩, TDZ

남아 있는 게시글 이름은 이건데 변경 된 후에 임시 저장되서 다른 이름으로 되어있는거 같습니다.

감사합니다 ㅎㅎ

**Comment by winverse** [comment]
안녕하세요 Velog를 이용해주셔서 감사합니다 :)

해당 관련 기록을 조회하였으나 안타깝게도 
요청 주신 제목의 글 중, 내용이 존재하는 것이 없습니다. ㅜㅜ

향후 관련 로직을 수정하여 조금더 이런 상황에 도움이 되도록 변경하겠습니다.

좋은 하루 보내세요 :)

**Comment by winverse** [comment]
안녕하세요.

전에 로직을 개선한다는 말씀을 드렸는데, 글을 공개로 전환하고나서 다시 수정 하려고 할때, 변경 사항들이 기록되도록 하였습니다.
[여기](https://github.com/velopert/velog-server/pull/171)서 관련 내용을 확인할 수 있습니다.

감사합니다 :)

**Comment by EunoChoi** [comment]
추가 안내 감사드립니다 :)

임시 저장이 안되었던 문제 원인 추측을 좀 해봤는데요.
작성중 상태에서 아무글도 작성 안한상태로 탭을 방치하다 엣지 브라우저 탭 에코 모드가 된거 같습니다.
아마..  그 상태에서 글 작성을해서 버그가 생긴게 아닌가.. 싶습니다 ㅎㅎ
지금 생각해보니 '임시저장되었습니다.' 안내를 보지 못했던것 같아요 ㅠ
