### ISSUE TITLE
임시저장되면 작성되는 위치가 최상단으로 강제로 이동되는 문제

### ISSUE THREAD

**Issue by WonHeeSoo** [velopert/velog-client#52]
운영체제 Window 10 64bit
브라우저 Chrome 웹, FireFox 웹

실험해보니 새 글을 작성할 때는 임시저장 메시지가 이제 안나와서 확인은 불가하지만 강제로 상단으로 이동하지 않습니다.
문제점
1. 임시 글을 불러와서 작성할 때는 전과 같이 약 10초 뒤에 임시저장되면서 작성되는 위치가 강제로 상단으로 이동됨을 확인했습니다.
2. 임시 저장 버튼을 눌러도 작성되는 위치가 상단으로 이동됨을 확인했습니다.

**Comment by velopert** [comment]
흠... 재현하기가 어렵네요 ㅠㅠ 윈도우로 해보고 있는데 문제없이 잘 작동하고있습니다 

혹시 크롬 버전도 알려주실수있을까요?

**Comment by WonHeeSoo** [comment]
최신 버전으로  버전 80.0.3987.100(공식 빌드) (64비트) 입니다.

죄송하게도 제가 말을 이해가 안되게 써서 그런거 같아 GIF를 남깁니다.

![bug](https://github.com/WonHeeSoo/About-My-Velog/blob/master/GIF/Bug/WriteTeleport.gif?raw=true)

위의 GIF는 글을 작성하고 약 10초 뒤에 작성되는 위치가 이동되는 것을 찍은 것입니다.
아마 제가 말하는 위치가 이동했다는 말이 개발자님에게는 다른 의미로 들린 것 같아 이렇게 올립니다.

**Comment by velopert** [comment]
Windows 10 Chrome 80.0.3987.100
재현이 안되네요 ㅠㅠ

Firefox에서 재현이 되는 것을 확인했습니다! 
시간 되는대로 고쳐볼게요~!

**Comment by velopert** [comment]
허허.. 어제 새벽엔 분명히 Win10 파이어폭스에서 재현이 됐는데 오늘은 또 안되네요.. 
오늘 마크다운 에디터 쪽에 성능 개선을 좀 했는데, 이 이슈가 혹시 고쳐졌는지? 한번 확인 부탁드립니다.

감사합니다~!

**Comment by WonHeeSoo** [comment]
Window 10 파이어폭스, 크롬
주로 사용하는 두가지 브라우저가 여전히 그 현상이 있고 다른 컴퓨터로 해봤는데 마찬가지 이네요;;

**Comment by velopert** [comment]
신기하군요.. 오늘 윈도우 노트북 빌려서 한번 확인해보겠습니다.

데스크탑 / VM에서는 문제 없더라구요 ㅠ

혹시 화면의 해상도도 알 수 있을까요?

**Comment by WonHeeSoo** [comment]
둘다 1920 1200 입니다.

**Comment by velopert** [comment]
으하하 알고보니 윈도우 이슈 아니였습니다... 

GraphQL 과 useEffect 관련 이슈였네요.
드디어 고쳤어요. 야호~!

**Comment by whybein** [comment]
임시저장하고 상관없이 자동으로 커서가 제일 위로 주르륵 올라가는 경우가 자주 발생합니다ㅜ
노트북으로 우분투 크롬에서 돌리고 있습니다

**Comment by velopert** [comment]
더 제대로 해결을 해야 될 것 같네요 :) 일반적인 케이스는 해결이 됐는데 임시저장하는 시점에 작성을 한다면 주루륵 올라가는 현상이 발생 할 수 있겠네요.
