### ISSUE TITLE
[문의] 벨로그 태그 관련해서 문의드립니다.

### ISSUE THREAD

**Issue by euisuk-chung** [velopert/velog-client#520]
![image](https://github.com/velopert/velog-client/assets/44948482/814a3397-85eb-4268-95be-ad3100df70ef)

현재 Tag 순서가 게시글의 개수 순으로 나열됩니다.

혹시 해당 부분에 대한 Tag Order 방법을 오름차순으로 변경할 수있는 방법이 없을까요?

**Comment by winverse** [comment]
안녕하세요 의견주셔서 감사합니다.

해당 기능은 내부에서 논의 중에 있습니다!
조금만 시간을 갖고 기다려주시면 감사하겠습니다

Velog를 이용해주셔서 감사합니다 :)
