### ISSUE TITLE
글이 안 보이고 검색하면 임시저장글이 보이는 문제

### ISSUE THREAD

**Issue by kngsujng** [velopert/velog-client#521]
안녕하세요. 벨로그 잘 이용하고 있는 사용자입니다. 
2~3일에 걸쳐 쓴 글(next-auth 관련 글)이 리스트에 나오고 있지 않아서 문의드립니다. 
해당 글을 찾다가 제 벨로그에 "next-auth"라는 글을 찾다가 게시글을 발견했지만, 
빠르게 해당 글을 클릭하지 않으면 사라지는 문제를 발견했습니다. 
또한, 해당 글이 전부 나오지 않고 임시저장했던 초안글로 바뀌었습니다 ㅜㅜ 
제 벨로그 주소는 https://velog.io/@kngsujng/posts 입니다.

**Comment by winverse** [comment]
안녕하세요. 

해당 글이 초안 글(임시 저장글)이 되면 [https://velog.io/saves](url) 임시 글 리스트에 나온다는 점 안내드립니다.
또한 next-auth 주제로 작성하신 글 중 `소셜 로그인` 관련 부분만 기록이 남아 있어서 도움드릴 수 있을거 같습니다.

Velog를 이용함에 있어 불편을 드려 죄송합니다.
