### ISSUE TITLE
[버그 제보] Velog 사이트 접속 불가 (CORS)

### ISSUE THREAD

**Issue by hyebinnn** [velopert/velog-client#525]
안녕하세요. velog 접속이 불가하여 현재 이슈를 알려드리고자 글을 작성하게 되었습니다.

## 이슈 내용
1. 현재 velog 사이트 접속 자체가 불가능합니다.
콘솔과 네트워크 확인 결과, graphQL에서 발생한 CORS 에러 같습니다.
<img width="1624" alt="image" src="https://github.com/velopert/velog-client/assets/76420055/f0b58e14-550b-48c9-a4ee-fcdc48b4c91c">
<img width="542" alt="image" src="https://github.com/velopert/velog-client/assets/76420055/f1492e02-b2bc-4cce-b606-56efc0dc2b3b">

<br><br>

2. 개인 포스트도 접속이 불가합니다. 404 에러가 뜹니다.
<img width="1502" alt="image" src="https://github.com/velopert/velog-client/assets/76420055/69a9c445-e8c4-4aa7-b4b8-f684db76c714">

<br><br>

확인 부탁드리겠습니다. 감사합니다.

**Comment by winverse** [comment]
어제(2024-03-06) 서버 이슈가 발생했습니다.
사유는 과도한 트래픽 발생이며, 현재는 서버 분산 및 코드 개선 작업을 진행하고 있습니다.

이용에 불편을 드려 죄송합니다.
