### ISSUE TITLE
게시글 자동 비공개 처리 문제

### ISSUE THREAD

**Issue by EunoChoi** [velopert/velog-client#526]
저번에 공개로 전환해주셨었는데
썸네일 수정하고 나니 다시 비공개 처리되고있습니다. ㅠㅠ

처리 부탁드립니다 ㅎㅎㅎ 감사합니다!!  :)

@eunocode
조각조각 - 리액트 렌더링(브라우저 렌더링, 가상돔)
https://velog.io/@eunocode/조각조각-리액트렌더링

**Comment by winverse** [comment]
Velog를 이용해주셔서 감사합니다.

요청해주신 게시글은 공개 처리 되었습니다.
또한 언제든지 요청 주시면 빠르게 확인하여 처리하도록 하겠습니다.

감사합니다.
