### ISSUE TITLE
게시글 eng 자동 필터링 이슈 공유드립니다

### ISSUE THREAD

**Issue by kim-kyoungyeon** [velopert/velog-client#527]
`customer` `support `

위 단어를 한 줄에 연속으로 쓰면 비공개 처리됩니다.
한 단어씩 쓰면 문제 없구요.

에러 코드 기록 겸 업로드 하다가 비공개 되길래 한단어 한단어 지워서 발견했습니다
꼭 issue 처리 부탁드립니다.

**Comment by winverse** [comment]
Velog이용에 불편을 드려서 죄송합니다.

현재 해당 키워드는 필터 리스트에서 제거가 되었으며,
앞으로 개선을 통해서 이용에 불편함이 없도록 하겠습니다.

의견주셔서 감사합니다 :)
