### ISSUE TITLE
자동 비공개 처리

### ISSUE THREAD

**Issue by EunoChoi** [velopert/velog-client#528]
안녕하세요. 자동 비공개 처리 문의드립니다.

죄송합니다. 비공개 처리되는거 잊고 이미지 교체후 글 수정해서 다시 비공개 처리되고있습니다. ㅠㅠ
처리  감사합니다!! :)

@eunocode
조각조각 - 리액트 렌더링(브라우저 렌더링, 가상돔)
[https://velog.io/@eunocode/조각조각-리액트렌더링](https://velog.io/@eunocode/%EC%A1%B0%EA%B0%81%EC%A1%B0%EA%B0%81-%EB%A6%AC%EC%95%A1%ED%8A%B8%EB%A0%8C%EB%8D%94%EB%A7%81)

**Comment by winverse** [comment]
안녕하세요. 이번주 내로 자동 비공개 처리 기능이 개선 되어 배포 예정입니다.

힘드시겠지만 그 전까지 이렇게 요청 부탁드리도록 하겠습니다.

Velog를 이용 해주셔서 감사합니다 :)
