### ISSUE TITLE
새 글 작성 시 오류

### ISSUE THREAD

**Issue by zeromok** [velopert/velog-client#531]
안녕하세요.

https://velog.io/@dainel/posts
위 주소의 벨로그를 이용중인 사용자입니다.

새글작성 후 업로드를 하게되면 https://velog.io/@zeromok/posts 으로 url 바뀌어 업로드 되고 있습니다.
해당 오류 확인한번 부탁드립니다.

감사합니다. 좋은하루보내세요 :)

**Comment by winverse** [comment]
Velog 이용중에 불편을 드려서 죄송합니다.

한번 브라우저 시크릿 모드에서 velog 접속 -> 로그인 -> 글 작성 한번 확인 부탁드려도 괜찮을까요? 

오늘도 좋은 하루 보내세요 :)

**Comment by zeromok** [comment]
시크릿모드에서는 잘 됩니다...!

**Comment by winverse** [comment]
확인 감사합니다 :)

한번 브라우저에서 F12 ->  Application -> Storage -> clear site data 부탁드리겠습니다. 

그럼 좋은 하루 보내세요 ~
