### ISSUE TITLE
비공개 글 사라짐

### ISSUE THREAD

**Issue by peeerr** [velopert/velog-client#532]
https://velog.io/@peeeeer/posts

어제 벨로그 글을 비공개로 두 개 올렸는데 오늘 벨로그 들어가보니 다 없어져있습니다..
일시적인 오류인줄 알았는데 복구가 안되네요 비공개 글이 사라진 적은 한번도 없었는데 왜 갑자기 사라졌을까요

**Comment by winverse** [comment]
Velog를 이용하는데 불편을 드려 죄송합니다.

혹시 작성하신 글의 제목이 
- Elastic Beanstalk + Github Actions 배포 자동화 + 무중단 배포 (1)
- Elastic Beanstalk + Github Actions 배포 자동화 + 무중단 배포 (2)

맞는지 확인 부탁드려도 될까요?

그럼 좋은 하루 보내세요 :)

**Comment by peeerr** [comment]
@winverse 로그아웃 로그인 많이 해봤는데 안되네요. 폰으로 체크해봐도 똑같습니다..

**Comment by winverse** [comment]
안녕하세요.
제보해주셔서 감사합니다.

해당 기능에 문제가 있던 것으로 파악 되었습니다.
지금은 해결이 완료 되었습니다. 

Velog 이용에 불펴을 드려 죄송하고 또 감사합니다.
