### ISSUE TITLE
원래 velog 다크모드 가능했지않나요?

### ISSUE THREAD

**Issue by Minssuy99** [velopert/velog-client#533]
간만에 velog 작성을 다시 시작하려하는데 한달전만해도 다크모드였던거같은데
다크모드가 사라졌나요?

그리고 우측 상단 내 프로필사진 클릭 > 설정 을 누르면 로그인을 하라는 창이 뜨는데, 로그인을 해도 똑같이 로그인을 하라는 반복적인
창만 계속해서 나타납니다.

**Comment by winverse** [comment]
안녕하세요.

알림 기능이 추가 됨에 따라서 부득이하게 다크 모드 기능이 내 프로필 -> 설정으로 옮기게 되었습니다.

다만, @Minssuy99 님께서 로그인 과정에서 불편을 겪고 계신것으로 보이는데 이용에 불편함을 드려 죄송합니다.

혹시 괜찮으시면 F12 -> Application ->  Storage 로 가셔서 clear site data 한번 부탁드려도 될까요?
현재 관련 부분 [업데이트](https://github.com/velog-io/velog/commit/7bd6d2fa38abd16233ad6da281636bde5bf273a1) 진행중이나 빠른 해결을 위해서 안내 드립니다.

문의 주셔서 감사합니다.
좋은 하루 되세요 :)

**Comment by winverse** [comment]
안녕하세요 제보해주셔서 감사합니다.

다크모드는 설정 페이지에서 확인이 가능합니다만,
해당 기능에 이슈가 있었고 현재는 해결 되었습니다.

덕분에 빠르게 문제를 파악할 수 있었습니다.
감사합니다 :)
