### ISSUE TITLE
다크모드 안돼요

### ISSUE THREAD

**Issue by kor-bim** [velopert/velog-client#535]
다크모드 버튼 있지 않았나요? 
로컬스토리지 theme 값 강제로 바꿔서 사용해야하나요?

**Comment by winverse** [comment]
안녕하세요 알림 기능이 추가 되면서 다크 모드가 개편되었습니다.

현재 로그인 -> 설정 페이지에서 다크 모드를 확인 하실 수가 있습니다.

감사합니다 :)
