### ISSUE TITLE
Bug: 글 작성시 미리보기에서는 이미지 크기 조정이 작동하나 실제 글은 이미지 크기 조정이 안되는 현상

### ISSUE THREAD

**Issue by Imagine-Choi** [velopert/velog-client#536]
글을 작성할때, 밑의 사진과 같이 이미지 첨부 할 때` <img src="" width="" height="" >`방식이 미리보기에서는 잘 작동되지만
<img width="50%" alt="스크린샷 2024-03-23 오후 3 41 14" src="https://github.com/velopert/velog-client/assets/80382025/aa65e471-d92a-4c60-a943-3bf79ce512e9">

글을 완성하면 반영이 되지 않습니다.
<img width="50%" alt="스크린샷 2024-03-23 오후 3 41 32" src="https://github.com/velopert/velog-client/assets/80382025/abd2d5e9-6452-4a61-a0e5-824a44876de4">

cdn에서 제공되는 이미지는 축소가 안되는 것처럼 보입니다.

**Comment by Imagine-Choi** [comment]
. issue 이전

**Comment by winverse** [comment]
처리가 늦어져서 죄송합니다 ㅜㅜ
