### ISSUE TITLE
자동 비공개 해제 부탁드립니다.

### ISSUE THREAD

**Issue by rlatkd** [velopert/velog-client#539]
블로그 이전중이라 제가 쓴 글 그대로 복붙하는데
자꾸 자동으로 비공개 걸리네요 해제 부탁드립니다.

https://velog.io/@kata/level-1-%EB%8B%AC%EB%A6%AC%EA%B8%B0-%EA%B2%BD%EC%A3%BC-178871

https://velog.io/@kata/level-1-%ED%81%AC%EA%B8%B0%EA%B0%80-%EC%9E%91%EC%9D%80-%EB%B6%80%EB%B6%84%EB%AC%B8%EC%9E%90%EC%97%B4-147355

https://velog.io/@kata/level-1-%EA%B0%80%EC%9E%A5-%EA%B0%80%EA%B9%8C%EC%9A%B4-%EA%B0%99%EC%9D%80-%EA%B8%80%EC%9E%90-142086

https://velog.io/@kata/level-1-%EA%B0%80%EC%9E%A5-%EB%A7%8E%EC%9D%B4-%EB%B0%9B%EC%9D%80-%EC%84%A0%EB%AC%BC-258712

https://velog.io/@kata/level-1-K%EB%B2%88%EC%A7%B8%EC%88%98-42748

https://velog.io/@kata/level-1-%EB%82%B4%EC%A0%81-70128

https://velog.io/@kata/level-1-%EC%9D%8C%EC%96%91-%EB%8D%94%ED%95%98%EA%B8%B0-76501

https://velog.io/@kata/level-1-%EC%9D%8C%EC%96%91-%EB%8D%94%ED%95%98%EA%B8%B0-76501

https://velog.io/@kata/level-1-%EB%B6%80%EC%A1%B1%ED%95%9C-%EA%B8%88%EC%95%A1-%EA%B3%84%EC%82%B0%ED%95%98%EA%B8%B0-82612

https://velog.io/@kata/level-1-%EC%97%86%EB%8A%94-%EC%88%AB%EC%9E%90-%EB%8D%94%ED%95%98%EA%B8%B0-86051

https://velog.io/@kata/level-1-%EC%B5%9C%EC%86%8C%EC%A7%81%EC%82%AC%EA%B0%81%ED%98%95-86491

https://velog.io/@kata/String

https://velog.io/@kata/Polymorphism

https://velog.io/@kata/Interface

https://velog.io/@kata/Collection

https://velog.io/@kata/File

https://velog.io/@kata/IO

https://velog.io/@kata/Enum

https://velog.io/@kata/Thread

https://velog.io/@kata/Multi-Thread

https://velog.io/@kata/Lambda

**Comment by winverse** [comment]
안녕하세요 Velog 이용에 불편을 드려 죄송합니다.

자동 비공개 로직 중에 5분동안 작성된 글의 개수가 10개를 넘어가면 비공개로 처리 하도록 되어 있습니다..
이점 유의하시길 바라며 작성하신 글들의 비공개를 해제 했습니다. 

감사합니다 :)
