### ISSUE TITLE
계속 자동 비공개 처리 됩니다

### ISSUE THREAD

**Issue by shinbiiiii** [velopert/velog-client#541]
안녕하세요. 글이 계속 자동으로 비공개 처리가 됩니다. 어느 부분이 문제인건지 알 수 있을까요??

주소:
https://velog.io/@bibibig/In-app-purchase-IAP%EC%9D%B8%EC%95%B1-%EA%B2%B0%EC%A0%9C-6k5etgkg

**Comment by winverse** [comment]
안녕하세요 처리가 늦어져서 죄송합니다.

해당 게시글은 공개로 전환되었습니다.

다만, 어떤 사유로 비공개로 처리가 되었는지는 공유가 어려운 점을 양해 부탁드립니다.

더욱이 게시글 자동 비공개 기능은 계속 개선해 나가고 있는 과정에 있습니다.
이용에 불편을 드려 죄송하고 더욱 나은 서비스로 보답하도록 하겠습니다.
감사합니다 :)
