### ISSUE TITLE
[Bug] Velog Bug Issue

### ISSUE THREAD

**Issue by osohyun0224** [velopert/velog-client#548]
안녕하세요, 벨로그를 잘 쓰고있는 프론트엔드 개발자입니다.
벨로그를 우선 개발해주셔서 정말 감사드립니다. 매일 잘 쓰고있습니다:)
더 벨로그가 발전되길 바라는 마음에 이렇게 버그 제보를 드리려고 합니다..!

1. 시리즈 날짜 최신 업데이트 버그
시리즈를 보면 "마지막 업데이트 YYYY년 MM월 DD일" 이렇게 표시되어있습니다. 하지만 이 시리즈의 최신 업데이트된 글의 날짜는 훨씬 이후입니다. 여기서 표시되는 마지막 업데이트 날짜는 시리즈가 생성된 날짜(현재)가 아니라 이 시리즈의 최신 포스팅 날짜인게 맞지 않을까 라는 생각이 들어 제보하게 되었습니다.

(1) 시리즈 표시
![image](https://github.com/velopert/velog-client/assets/53892427/bba942aa-dc30-4d76-8776-cb51df77beca)

(2) 해당 시리즈의 최신 글 포스팅 날짜
![image](https://github.com/velopert/velog-client/assets/53892427/8186a46c-30d7-4503-9de4-46d89da0396e)

2. 글의 통계 조회에서 오늘, 어제가 보이지 않는 버그

이 버그는 원래 없었는데 갑자기 언젠가부터 아래 그래프와 오늘, 어제 카운트가 표시되지 않습니다 전체 조회수만 조회되어서 이점이 버그인 것 같아 제보하게 되었습니다.

![image](https://github.com/velopert/velog-client/assets/53892427/4ff4221c-b3cb-4beb-ade4-0557d4a57a58)

벨로그와 같이 좋은 서비스를 만들어주셔서 진심으로 감사드립니다🙆🏻‍♀️

**Comment by winverse** [comment]
안녕하세요. 제보 감사합니다!

1번 관련해서는 내부에서 논의 하도록 하겠습니다.
2번은 통계 관련 query 이슈로 아쉽게도 기능을 제한 하고 있습니다. (죄송합니다 ㅜㅜ)

향후 변경점이 있다면 여기에 댓글을 남기도록 하겠습니다. 

Velog 를 아껴주시고 이용해주셔서 감사합니다 :)
