### ISSUE TITLE
개시물에 비공개 처리되었습니다. 공개 처리 부탁드립니다.

### ISSUE THREAD

**Issue by printwd** [velopert/velog-client#550]
https://velog.io/@pwd/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EB%AA%A8%EB%8D%B8

개시물이 비공개 처리되었습니다. 비공개 키워드가 들어간것도 아닌데 비공개 처리가 되었네요.

**Comment by winverse** [comment]
안녕하세요 Velog 이용에 불편을 드려 죄송하고 
또 좋은 글을 남겨주셔서 감사합니다.

해당 글은 비공개 알고리즘에 의해서 자동 비공개 처리가 되었습니다.(오늘 오전 11시 - 오후1시)
불편을 드려서 죄송하고 향후 개선해나가도록 하겠습니다.

해당 게시글은 공개로 변경 되었습니다 

감사합니다 :)
