### ISSUE TITLE
왜 자동 비공개가 될까요?

### ISSUE THREAD

**Issue by rlarjsdn3** [velopert/velog-client#552]
힘들게 쓴 글이 자동으로 비공개가 되니 속상하네요ㅜㅜ 

글 제목은 "Swift Macro 알아보기"입니다. 

Velog주소는

 https://velog.io/@rlarjsdn3/posts

입니다. 

차단되는 키워드가 무엇인지 알려주는 기능이라도 있었으면 좋겠습니다ㅜㅜ

**Comment by winverse** [comment]
안녕하세요. 

Velog 이용에 불편을 드려서 죄송합니다

해당 게시글은 공개로 전환된 것으로 보여집니다.

차단되는 키워드를 알려주면 이를 악용할 소지가 있어 어렵다는 판단이 들었습니다. 이점 양해 부탁드립니다.

비공개 알고리즘은 개선중에 있으며 더욱 좋은 사용자 경험으로 보답해드리겠습니다.

감사합니다 :)
