### ISSUE TITLE
자동 비공개처리 전환 요청드립니다

### ISSUE THREAD

**Issue by jae6269** [velopert/velog-client#555]
https://velog.io/@jae6269/%EC%96%B4%EB%96%BB%EA%B2%8C-React19%EC%9D%B4-%EC%9D%B8%ED%84%B0%EB%84%B7%EC%9D%84-%EB%8D%94-%EB%8A%90%EB%A6%AC%EA%B2%8C-%ED%95%98%EB%8A%94%EA%B0%80-%EC%9D%98-%EC%9D%B4%EC%8A%88-%EB%B2%88%EC%97%AD-.1

게시글의 링크인데 계속 자동 비공개처리가 되어서 요청드립니다

**Comment by winverse** [comment]
안녕하세요!

불편을 드려 죄송합니다.
해당 게시글은 공개로 전환되었습니다.

앞으로도 이용 중에 어려움이 있다면 언제든지 문의 주시길 바랍니다.

감사합니다 :)
