### ISSUE TITLE
글이 계속 사라집니다. (비공개로 전환되는 것 x)

### ISSUE THREAD

**Issue by KimGaeun0806** [velopert/velog-client#556]
글을 출간하면 몇 분 간은 그대로 있다가 어느순간 사라져 있습니다.
확인해보면 임시저장글에 들어가있는데, 아무리 수정을 해도 수정 이전 버전만 남아있습니다.
임시저장글로 다시 출간을 해도 글이 정상적으로 업로드되지 않습니다.

https://velog.io/@greencloud/%EC%8C%88%EB%BD%95%ED%95%98%EA%B2%8C-Lighthouse-%EC%9E%90%EB%8F%99%ED%99%94%ED%95%98%EA%B8%B0 
수정 이전 내용이 남아있는 임시저장글 링크입니다.

**Comment by winverse** [comment]
제보해주셔서 감사합니다!

빠른 시일 내에 알아볼 수 있도록 하겠습니다.

그때 다시 코멘트 드릴게요!

**Comment by alemem64** [comment]
똑같은 문제를 저도 겪고 있습니다. 언제 해결되나요? 글 작성이 전혀 되지 않습니다.

**Comment by winverse** [comment]
안녕하세요. 

임시 저장된 글을 불러올때, 이전 작성 내용을 불러오지 못하던 버그를 수정하였습니다. [#568](https://github.com/velopert/velog-client/pull/568)

간단한 문제임에도 오랜 시간 걸린점 죄송합니다.

**Comment by KimGaeun0806** [comment]
해결해주셔서 감사합니다 :)
