### ISSUE TITLE
신고기능이 없나요??

### ISSUE THREAD

**Issue by 22bbn2** [velopert/velog-client#558]
https://velog.io/@huiji/3D-Any-%EC%82%AC%EC%A7%84%EA%B3%BC-%EB%B9%84%EB%94%94%EC%98%A4%EB%A5%BC-3D-%EC%98%81%EC%83%81%EC%9C%BC%EB%A1%9C-%EC%89%BD%EA%B2%8C-%EB%B3%80%ED%99%98

해당 글이 현재는 지워졌는데 굉장히 대중교통에서 볼 수 없는 수준의 썸네일 사진이었는데요,
이런 썸네일은 뭔가 19처리라던가 신고기능이 있어야하지 않을까요..
어찌보면 커뮤니티 사이트인데 신고기능을 못찾아서 문의드립니다.

**Comment by winverse** [comment]
문의 주셔서 감사합니다. 

현재 아쉽게도 신고 기능은 없습니다 ㅜㅜ

다만 velog slack이 있는데, 거기에 남겨주시면 그나마 빠르게 처리 하도록 하겠습니다.
여의치 않으시면 issue란에 남겨주세요!

감사합니다 :)
