### ISSUE TITLE
시리즈 마지막 업데이트 시간

### ISSUE THREAD

**Issue by tacowasabii** [velopert/velog-client#559]
https://velog.io/@tacowasabii/series

시리즈별 마지막 업데이트 시간이 제대로 반영이 안됩니다

**Comment by winverse** [comment]
제보 주셔서 감사합니다!

해당 문제는 [commit](https://github.com/velog-io/velog/commit/d1ced0388392091cc605d3f7ba42b555da1483bc)에서 확인 가능합니다.

Velog를 이용해주셔서 감사합니다 :)
