### ISSUE TITLE
계속 비공개 되어서 답답해서 글을 못쓰겠습니다 ㅠㅠ 

### ISSUE THREAD

**Issue by PKHDSECO** [velopert/velog-client#560]
https://velog.io/@21c_enthics/AI%EC%9C%A4%EB%A6%AC%EC%99%80-%EA%B8%B0%EC%97%85%EC%9D%98-%EC%82%AC%ED%9A%8C%EC%A0%81-%EC%B1%85%EC%9E%84%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC

비공개 해제 부탁드리겠습니다... ㅠㅠ 

이유를 전혀 파악할 수가 없으니 답답해서 글을 못쓰겠습니다...

**Comment by winverse** [comment]
불편을 드려 죄송합니다 

해당글은 공개로 전환되었습니다.

글 비공개 알고리즘 개선에 노력을 하도록 하겠습니다
