### ISSUE TITLE
글 수정하기에서 새로 시리즈 생성 이후 해당 시리즈에 글을 등록하면 등록되지 않는 현상

### ISSUE THREAD

**Issue by C12H22O12** [velopert/velog-client#562]
![Screenshot_20240721_135426_Samsung Internet](https://github.com/user-attachments/assets/cfb951ef-7e73-4452-a646-ac3017599e1a)

글을 출간하는 과정 중 새로 시리즈를 추가하고, 해당 시리즈에 작성한 글을 등록하면 등록이 올바르게 되지 않는 현상이 있습니다.
- 글이 등록된 후 등록이 완료된 페이지로 이동합니다. 이 때 외부에서 해당 글의 url에 접속할 경우 404 화면이 뜹니다.
- 등록된 시리즈는 존재합니다.
- 메인과 등록된 시리즈에 새 글이 등록되어있지 않습니다. 시리즈는 글이 0개로 뜹니다.

24.07.21 19:28 추가
#556 과 같이 일정 시간이 지난 이후 글이 삭제되는 현상을 발견했습니다

**Comment by winverse** [comment]
안녕하세요 제보 남겨주셔서 감사합니다!

해당 버그를 재연하고 싶은데 여의치 않습니다 ㅜㅜ

혹시 현재도 발생하는 버그 일까요?

**Comment by winverse** [comment]
안녕하세요! 

여러 사람들의 도움으로 시리즈에 등록 된 글이 수정 되었을 경우 임시 글로 이동하는 문제를 수정하였습니다.

Velog를 이용해주셔서 감사합니다!
