### ISSUE TITLE
제가 쓴 글이 자꾸 '비공개' 로 전환됩니다. 도와주세요 ㅠㅠ

### ISSUE THREAD

**Issue by CDR4733** [velopert/velog-client#563]
현재 계속 비공개로 바뀌는 글은

https://velog.io/@cdr4733/%EC%97%91%EC%85%80%EB%B3%B4%EB%8B%A4-%EC%89%BD%EA%B3%A0-%EB%B9%A0%EB%A5%B8-SQL-1%EC%A3%BC%EC%B0%A8

이 글입니다. 무엇이 문제일까요? 
해결 부탁드리겠습니다!! 감사합니다 ㅠㅠ

일단 'E-MAIL' 이라는 키워드가 문제가 된 것인가 싶어서
그 부분 삭제하고 글을 수정해놓기는 했는데...

비공개로 바뀌게 될 것인지 기다리고 있습니다 ㅠ
문단 하나하나 지워가며 확인 중이라..ㅠㅠ

혹시 제 정보가 필요하실 까봐 아래 메모 남깁니다.
@뒤에 있는 아이디는 cdr4733 이고,
벨로그 별명(?)은 Cozler 입니다.

**Comment by winverse** [comment]
안녕하세요 이용중에 불편을 드려 죄송합니다.

현재는 모든 게시글이 공개로 보여 집니다 !

Velog를 이용해주셔서 감사합니다 :)
