### ISSUE TITLE
비공개 좀 풀어주세요ㅜㅜ

### ISSUE THREAD

**Issue by taeri0327** [velopert/velog-client#566]
코딩 공부하면서 하루 종일 열심히 작성한 게시물인데
왜 인지 발행하면 자꾸 비공개 처리되네요ㅜㅜㅜ
이유라도 알려주시면 고칠게요ㅠㅠㅠ 전체공개로 바꿔주세요ㅜㅜ

https://velog.io/@taeri0327/2024.08.05월-슈퍼코딩-신입연수원-1주차-Day-1-후기

**Comment by winverse** [comment]
Velog 이용에 불편을 드려서 죄송합니다. 

해당 게시글은 공개로 전환 되었습니다!
