### ISSUE TITLE
글을 수정할때 글 업데이트 날짜가 수정되면서 시리즈의 순서가 바뀌는 일

### ISSUE THREAD

**Issue by S2gamzaS2** [velopert/velog-client#569]
7월 25일에 올린 게시글을 수정하였는데 게시 날짜가 오늘로 바뀌면서 시리즈 순서도 가장 아래(최신)로 변경되는 문제가 발생하였습니다

![image](https://github.com/user-attachments/assets/8365319c-5a5a-4acf-8539-19eccb473bc8)

**Comment by winverse** [comment]
제보해주셔서 감사합니다!

시리즈에 포함 되었던글이 업데이트 되면서 시리즈를 이탈(?)하던 문제를 해결했습니다.

Velog를 이용해주셔서 감사합니다!

**Comment by kyucchoi** [comment]
Hello Tetz's World!
