### ISSUE TITLE
댓글에 있는 코드 초록색? 왜 그럴까

### ISSUE THREAD

**Issue by velopert** [velopert/velog-client#57]
![image](https://user-images.githubusercontent.com/17202261/74465090-1a567e80-4ed8-11ea-84ae-9aaf83364f36.png)

**Comment by HADMARINE** [comment]
초록색 색깔을 일부러 내신거면 조금 진했으면 좋겠습니당!

**Comment by velopert** [comment]
ㅋㅋ 일부러 낸건 아닙니다...! 
실수였어용 ㅎㅎ
