### ISSUE TITLE
velog 에서 글을 수정 중에 임시저장이 되면 수정완료 후 글 작성일이 글을 처음 작성했던 시간이 아니라 수정한 시간으로 바뀌어버립니다.

### ISSUE THREAD

**Issue by ansm0403** [velopert/velog-client#570]
예전 글 수정 중 갑자기 작성일이 오늘로 바뀌었길래 다른 글도 어차피 수정할 것 있어서 해보니 같은 반응이었습니다. <br>
그래서 각 잡고 본문 수정량을 많이 바꿔보기도 하고, 태그를 바꿔보기도 하고, 공개설정, 시리즈 설정, 미리보기 사진 등 다 바꿔봤지만 <br>
오히려 이렇게 수정하니 작성일이 그대로 였습니다. <br>
그러다가 임시저장이 생각나서 원본글에 그냥 아무 문자 하나만 딱 입력하고 아무 설정도 바꾸지 않은채로 임시저장이 될 때까지 기다렸다가 수정하기 누르니 글 작성 날짜가 오늘로 바뀌었습니다. <br>
예전에는 수정을 오래해도 작성일이 안바뀌었던 것 같은데, 제가 눈치를 못챘던 것일까요? 아니면 오류일까요...

**Comment by winverse** [comment]
안녕하세요 제보 감사드립니다 :)

해당 이슈는 미리 [제보](https://github.com/velog-io/velog/issues/50) 되어서 현재 처리 되었습니다 

Velog를 이용해주셔서 감사합니다.
