### ISSUE TITLE
code blocks 하이라이팅에 docker가 지원이 안됩니다.

### ISSUE THREAD

**Issue by goldleo1** [velopert/velog-client#572]
![image](https://github.com/user-attachments/assets/9127098f-448b-41f5-9283-dd9e8136fe7f)
이런식으로 지원이 안됩니다.

- 벨로그 너무 좋습니다. 감사합니다 :)

**Comment by winverse** [comment]
안녕하세요 제보 주셔서 감사합니다!

이제 code block 영역이 docker를 지원하도록 [변경](https://github.com/velopert/velog-client/pull/575)하였습니다.

Velog를 이용해주셔서 감사합니다 :)

**Comment by goldleo1** [comment]
감사합니다!
