### ISSUE TITLE
글 수정 후 날짜 변경 문제

### ISSUE THREAD

**Issue by KimGaeun0806** [velopert/velog-client#576]
안녕하세요,
2023년에 작성한 글 내용을 2024년에 일부 수정했는데, 날짜가 변경되면서 해당 글이 목록의 최상단으로 올라왔습니다.
글을 수정하더라도 순서는 최초 글 작성 일자에 맞춰서 정렬하고 싶은데 방법이 없을까요? 
추가적으로 글 작성 일자는 2023년 12월 20일이며, 수정일자는 2024년 8월 13일인데 글 작성 일자가 2024년 7월 20일로 보이고 있습니다. 
이 부분도 수정되면 좋을 것 같습니다.

해당 글 링크입니다.
https://velog.io/@greencloud/%EB%B6%80%EC%8A%A4%ED%8A%B8%EC%BA%A0%ED%94%84-8%EA%B8%B0%EB%A5%BC-%EB%81%9D%EB%A7%88%EC%B9%98%EB%A9%B0-Feat.-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%82%B9%EB%8D%B0%EC%9D%B4-%ED%9B%84%EA%B8%B0

**Comment by winverse** [comment]
안녕하세요!

얼마전에 공개된 게시글은 수정하더라도 released_at 이 변경되지 않도록 수정하였습니다.

따라서 해당 게시글의 released_at을  2023년 12월 20일로 변경하도록 하겠습니다.

감사합니다 :)

**Comment by KimGaeun0806** [comment]
감사합니다 ㅎㅎ 😄
