### ISSUE TITLE
게시물이 자꾸 비공개로 전환됩니다.

### ISSUE THREAD

**Issue by 976520** [velopert/velog-client#577]
https://velog.io/@haensol/layout

문제될만한 요소가 있다면 알려주세요...

**Comment by winverse** [comment]
안녕하세요

불필요하게 비공개로 전환 되어 불편을 드려 죄송합니다

문제 될 만한 요소가 없어 해당 게시글은 공개로 전환되었습니다. 

감사합니다 :)
