### ISSUE TITLE
[이슈] Timeout 오류로 인해 게시글 저장 불가 및 중복 등록 문제 발생

### ISSUE THREAD

**Issue by euisuk-chung** [velopert/velog-client#583]
## Description:
출간하기 또는 수정하기 버튼 클릭 시 무반응이거나, "게시글 저장 불가"라는 오류 로그가 발생하고 있습니다. 해당 오류로 인해 사용자는 여러 번 버튼을 클릭하게 되었고, 그 결과 동일한 게시글이 시리즈에 중복 등록되었습니다.

최근 들어서 이러한 이슈가 계속 발생하는 것 같습니다... ㅠ

## Steps to Reproduce:
1. 게시글 작성 또는 수정 후 **출간하기** 또는 **수정하기** 버튼을 클릭.
2. 버튼 클릭 시 간헐적으로 아무런 반응이 없거나, **Timeout 오류** 및 **게시글 저장 불가** 로그 발생.
3. 여러 번 버튼을 클릭했을 때, 게시글이 중복 등록됨.
4. **수정 중입니다**에서 넘어가지 않음

## Expected Behavior:
- 정상적으로 게시글이 저장되고 시리즈에는 중복 등록이 발생하지 않아야 합니다.

## Actual Behavior:
- 출간하기/수정하기 버튼이 클릭될 때, 무반응이거나 오류가 발생합니다.
- 게시글은 정상적으로 올라가나, 동일한 글이 시리즈에 여러 번 등록되는 문제가 있습니다.

**Comment by winverse** [comment]
벨로그 이용중에 불편을 드려서 죄송합니다

해당 오류는 search engine 오류로 파악 되었고 현재는 해결된 상항입니다.

제보 주셔서 감사합니다!
