### ISSUE TITLE
미리보기에는 적용이 되는데, 막상 출간하면 형식이 제대로 적용이 안되고 있습니다.

### ISSUE THREAD

**Issue by 2JAE22** [velopert/velog-client#587]
![image](https://github.com/user-attachments/assets/69bf33fa-a57c-426e-853c-0a98ec53f18d)

이렇게 빨간 글씨와 백틱에  한게 나와야 하는데,

![image](https://github.com/user-attachments/assets/3c688dfa-67ec-4e1f-b3c3-112a57cb1245)
이런런식으로 안나옵니다. 빨간색이랑 글씨 크기가 사라졌습니다..

**Comment by winverse** [comment]
마크다운을 작성할때, 스타일 관련된 attribute가 제거 되도록 하였는데, 내부에서 논의 해보도록 하겠습니다.
