### ISSUE TITLE
velog에 첫 글을 게시하였는데 자꾸 자동으로 비공개처리가 됩니다.

### ISSUE THREAD

**Issue by beckham12345678** [velopert/velog-client#588]
혹시 어떤게 문제인지라도 알려주실 수 있나요?? 수정하겠습니다!
velog 아이디는 '/@yhs981209'이고,
글 제목은 '우당탕탕 비전공자 코딩 생초보 탈출기(1)' 입니다.

**Comment by winverse** [comment]
불편을 드려서 죄송합니다.

해당 게시글은 공개로 전환되었습니다 :)

좋은 하루 보내세요!
