### ISSUE TITLE
게시글 작성 시 스팸 키워드 포함 확인 기능

### ISSUE THREAD

**Issue by ghost** [velopert/velog-client#591]
게시글 작성 후 스팸/악의성 게시글이 아님에도 불구하고 자동 비공개가 계속 되는 중입니다.
그래서 한 문단씩 끊어서 올리고, 확인하고, 수정하는 과정을 지금도 거치고 있습니다.

게시글 작성 후 등록 전 어떤 키워드가 차단인지,
그것이 스팸에 악용이 된다면 최소한 차단 키워드가 포함되어있는지 확인할 수 있었으면 좋겠습니다.

감사합니다.

**Comment by winverse** [comment]
안녕하세요

Velog 이용중에 스팸 관련 해서 Ghost 님이 말씀해주신것 처럼 여러번 요청이 있었습니다.

하지만, 스팸 키워드가 공개 되는 것은 다른 방식으로 악용될 수 있는 여지가 있습니다.

하여, Velog에서는 스팸 처리하는 알고리즘을 좀더 개선하도록 노력 하겠습니다.

감사합니다.
