### ISSUE TITLE
비공개처리된 post 공개처리해주세요 ㅜㅜㅜ

### ISSUE THREAD

**Issue by bigone-77** [velopert/velog-client#593]
아래는 vitest 라이브러리 학습 후 기록한 포스팅입니다...!

https://velog.io/@bigone77/Vitest%EB%A1%9C-%ED%85%8C%EC%8A%A4%ED%8A%B8%ED%95%98%EA%B8%B0-%EB%8B%A8%EC%9C%84%ED%85%8C%EC%8A%A4%ED%8A%B8unit-test

**Comment by winverse** [comment]
안녕하세요!

velog 이용중에 불편을 드려 죄송합니다.

해당 게시글은 공개로 전환되었습니다

이용해주셔서 감사합니다 :)
