### ISSUE TITLE
비공개 해제 요청드립니다.

### ISSUE THREAD

**Issue by CalmForce3** [velopert/velog-client#597]
https://velog.io/@e0jooo/GANGenerative-Adversarial-Nets
제 첫 블로그 포스트인데 링크 모여있는 부분, 단어 조합을 바꿔도 공개 전환이 되질 않네요.
전환 부탁드립니다. 
velog cs분야에서 좋은 블로그 플랫폼이라고 해서 시작했는데...
공개 전환되어야 과제 채점을 받을 수 있어서 빠른 조치 부탁드립니다.

**Comment by winverse** [comment]
늦어져서 죄송합니다.

혹시 해결되셨을까요?
