### ISSUE TITLE
비공개 공개로 전환 부탁드립니다.

### ISSUE THREAD

**Issue by aiseungjun** [velopert/velog-client#598]
저의 논문 블로그 포스팅이고, 광고는 없습니다. 제 블로그로 학교에서 평가 받을 일이 있는데 한시가 급해서 빠른 수정 부탁드립니다. 감사합니다.
https://velog.io/@aiseungjun/Paper-review-Image-to-Image-Translation-with-Conditional-Adversarial-Nets

**Comment by winverse** [comment]
늦어져서 죄송합니다. 

게시글은 공개로 전환 되었습니다.
