### ISSUE TITLE
비공개 해제 부탁드립니다

### ISSUE THREAD

**Issue by jineey030** [velopert/velog-client#599]
https://velog.io/@jineey/CT-%EC%B5%9C%EC%86%8C-%EC%B5%9C%EB%8C%80-10818%EB%B2%88

해당 블로그 게시물이 자꾸 강제 비공개 처리가 됩니다!
해제 부탁드립니다 ㅠㅠ

**Comment by winverse** [comment]
비공개 처리가 해제 되었습니다.

이용에 불편을 드려 죄송합니다
