### ISSUE TITLE
비공개 해제 요청드립니다. 

### ISSUE THREAD

**Issue by gunheekim90** [velopert/velog-client#603]
자구 비공개로 돌아가는데 해제해주세요!

https://velog.io/@toughdev/%ED%95%AD%ED%95%B4-%ED%94%8C%EB%9F%AC%EC%8A%A4-Ai-%EC%88%98%EA%B0%95-%EC%86%94%EC%A7%81-%ED%9B%84%EA%B8%B0

**Comment by gunheekim90** [comment]
@winverse 해제 부탁드립니다.

**Comment by winverse** [comment]
늦어져서 죄송합니다. 

비공개 해제 해드렸습니다
