### ISSUE TITLE
프로필 사진 조절

### ISSUE THREAD

**Issue by kang-heewon** [velopert/velog-client#61]
프로필 사진 설정시 정방향 이미지가 아니면 깨집니다.
크롭할 영역을 정할 수 있으면 좋을 것 같습니다!

**Comment by velopert** [comment]
제가 기존에 `object-fit: cover` 설정을 일부 이미지에 처리하지 않아서 깨진 것 같습니다.
이제 이미지가 눌리는 현상은 사라졌을 것 입니다.

크롭을 하는 기능은 급한 기능은 아닌 것 같아서, 나중에 구현해보는걸로 하겠습니다!
감사합니다 :-)
