### ISSUE TITLE
길이가 긴 벨로그 제목

### ISSUE THREAD

**Issue by sq787** [velopert/velog-client#73]
![mfwktn wpgks](https://user-images.githubusercontent.com/22613611/74601555-dbe0df80-50e2-11ea-950f-5ffcbba91fa1.png)

두 가지 방법이 있습니다.
- 스타일을 수정할지 (Frontend)
- 길이 제한을 설정할지 (Backend)

는 @velopert 님이 선택하셔야 할 것 같습니다.

(본 이슈는 client와 server에 동시에 게시함)

**Comment by velopert** [comment]
https://github.com/velopert/velog-server/issues/11
