### ISSUE TITLE
임시저장 피드백 오류

### ISSUE THREAD

**Issue by sihoon-kim** [velopert/velog-client#75]
현상 : 설정 탭 -> 임시 글 -> 임시 저장 순으로 진행했을 시 

![issue 2](https://user-images.githubusercontent.com/60372355/74616453-27d76700-516b-11ea-98f3-3a249ed691b9.PNG)

위와 같은 피드백 UI가 표시되지 않고 있습니다.

에러 화면 
![issue](https://user-images.githubusercontent.com/60372355/74616464-39207380-516b-11ea-9eda-9742947f3923.PNG)

**Comment by velopert** [comment]
또 발생하면 이슈 다시 열어주세요 :D 
지난번에 수정된것같아서 닫습니다.
