### ISSUE TITLE
시리즈 화면 정렬 오류

### ISSUE THREAD

**Issue by MinhoLee93** [velopert/velog-client#80]
![image](https://user-images.githubusercontent.com/50879621/74705036-d3f57c80-5255-11ea-97b9-bb27ec337bb7.png)

https://velog.io/@minholee_93/series

현재 위와 같이 시리즈 목록 정렬이 제대로 되지 않습니다.
제 친구의 화면은 정상인걸로 보아..

데이터의 길이에 따라서 에러가 발생하는 것 같습니다.
확인 부탁드리겠습니다. :)

**Comment by velopert** [comment]
시리즈 탭에서는 태그를 보여주면 안됐었는데..! 그거 때문에 발생한 이슈 같네요!
오늘 저녁에 고치겠습니다.
