### ISSUE TITLE
임시저장 글이 발행됨

### ISSUE THREAD

**Issue by whybein** [velopert/velog-client#87]
https://velog.io/@swhybein/Django-model-%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0

안녕하세요.
오늘 오후에 'Django - bulk_create으로 csv파일 올리기' 와 비슷한 제목으로 글을 올렸는데
눌러보니 위의 임시저장 글이 연결되고 있습니다. url 주소는 임시저장글 제목에 해당되는데 저도 헷갈립니다. 혹시 원글을 복구할 수 있는 방법이 있을까요?

저 임시 글은 임시글 목록에는 있고 제 발행글 최신목록에는 없는 상황입니다.
원래 작성한 글은 임시글에도 없습니다. 오후에 슬랙에 올렸던 링크를 모바일에서 누르면 404가 뜨고 pc에서 누르면 저 임시글이 뜨는 상황입니다.

**Comment by velopert** [comment]
안녕하세요,

불편을 드려 죄송합니다.

정확히 어떤 원인으로 인하여 이런 이슈가 발생했는지는 파악하기가 힘드네요 ㅠㅠ
우선, 수동으로 복구를 해드렸습니다. 임시 글 목록에 가시면 글이 복구되어 있을 것입니다.

혹시 재현 할 수 있는 방법을 알아내시게 된다면..! 또 이슈 올려주세요.

감사합니다!

**Comment by whybein** [comment]
감사합니다! 집에 가는길에 아까 띄워놨던 최신글 리스트로는 들어가져서 텍스트를 복사해놨었네요
정확히 어떤 상황인지 모르지만 혹시나 발견하게 되면 이슈 드리겠습니다. 참 서버에 올렸어야 하는데 잘못올렸네요.
아무튼 복구해 주셔서 감사합니다^^

**Comment by whybein** [comment]
아 다시보니 모바일 최신글 피드에서 봤을때 제목은 정상인데 내용미리보기 부분이 임시글로 돼있었습니다.
