### ISSUE TITLE
프로필 이미지 깨짐

### ISSUE THREAD

**Issue by kwanwooi25** [velopert/velog-client#88]
v2 업데이트 해주신 이후로 처음 들어와 로그인 해봤는데 프로필 이미지가 제대로 표시되지 않고 있습니다.
devtools로 확인한 URL을 브라우저에 직접 입력하면 이미지가 브라우저에 표시되는게 아니라 다운로드가 되는데 그게 관련이 있는지는 모르겠습니다.

![Screen Shot 2020-02-20 at 5 56 47 PM](https://user-images.githubusercontent.com/28733869/74917523-f7155d00-540a-11ea-9415-5780bf1b6c76.png)

**Comment by velopert** [comment]
지금은 해결 된 것 같네요! 
혹시 따로 조치를 취하신게 있으신가요?

**Comment by kwanwooi25** [comment]
@velopert 
jpg파일로 바꿨습니다.
전에 프로필로 썼던 파일이 svg인데, 그게 원인인 것 같아요.
