### ISSUE TITLE
PC 화면 크기 조정시 글쓰기 버튼 사라짐

### ISSUE THREAD

**Issue by delmaSong** [velopert/velog-client#89]
PC 화면 윈도우 크기 조정시 글쓰기 버튼이 아예 사라져서, 작은 창에서 글 쓰려면 화면을 늘려서 글쓰기 버튼 클릭 후 다시 줄여야 해요. 확인해주세요.

**Comment by velopert** [comment]
모바일에서 글쓰기가 아직 구현되지 않아서 일단은 숨긴건데,
정말 모바일기기일때만 숨기거나, 모바일 작성을 최소한의 기능으로 구현하거나.. 해야겠습니다!
