### ISSUE TITLE
글쓰기 임시저장 후 나가는 버튼이 없음

### ISSUE THREAD

**Issue by delmaSong** [velopert/velog-client#90]
글쓰기 임시 저장 후 나가려면 무조건 뒤로가기만 해야해요
해당 화면에 벨로그 로고도 없고, 내 블로그로 이동하거나 밖으로 나갈 수 있는 버튼이 아예 없습니다.
확인 부탁드려요.

**Comment by velopert** [comment]
개선해보겠습니다!
