### ISSUE TITLE
글 조회수 기능 요청드려도 될까요??

### ISSUE THREAD

**Issue by MinhoLee93** [velopert/velog-client#92]
안녕하세요!
먼저 좋은 플랫폼 만들어 주셔서 감사합니다 :)

다름이아니라, velog에 글을 자주 쓰는데
쓰고난뒤 몇명이나 내 글을 봐줬을까? 하는 기대감이 
항상 생기더라구요 ㅎㅎ

혹시 간단하게나마 조회수 기능 추가 요청드려도 될까요?? :)
감사합니다.

**Comment by velopert** [comment]
서버에서 현재 수집 하고 있고,
Google Analytics API 를 통해서 통계를 볼 수 있는 기능도 언젠간 계획중이긴 한데... 빠른 시일내에 될 것 같지는 않아서
포스트 조회수만 본인이 볼 수 있도록 하는 기능은 금방 할 수 있을 것 같아서 한번 해보도록 하겠습니다!

**Comment by MinhoLee93** [comment]
@velopert 감사합니다 😁!!

**Comment by l4dboomer** [comment]
혹시 도입 아직 안됐나요..?ㅠㅠ

**Comment by znzkah** [comment]
@velopert 혹시 아직 안됐나요?ㅠㅠ

**Comment by davelee1030** [comment]
ㅠㅠ 안녕하세요 @velopert 조회수 기능은 작성자 본인에게 블로그 방향을 잡는데도 도움이되고 , 또 힘이 되기도 합니다. 공짜로 잘 쓰는 입장이지만 이 기능이 꼭 있었으면 좋겠어요...

**Comment by velopert** [comment]
드디어~ 구현됐습니다 :D
