### ISSUE TITLE
특정 문자 붙여넣기시 오류페이지로 이동 + 오류 페이지에서 "홈으로"버튼 동작 안함

### ISSUE THREAD

**Issue by sonsoohoon** [velopert/velog-client#93]
1. 특정 문자 붙여넣기시 오류페이지로 이동

`<constructor-arg index="0" ref="sqlSessionFactory" />`

위 텍스트를 에디터 화면에 붙여넣기 하면 
<img width="373" alt="ScreenClip" src="https://user-images.githubusercontent.com/12693226/75115140-52f81400-569f-11ea-9b27-fa4816342c36.png">
위와 같이 오류 페이지로 넘어갑니다.

2. 오류 페이지에서 "홈으로"버튼 동작 안함

벨로그 너무 잘 쓰고 있습니다. 벨로그가 많이 발전하길 바랍니다.
감사합니다.

**Comment by velopert** [comment]
해당 이슈 해결되었습니다.

다만, 여전히 입력하신 텍스트 작성하시면 컨텐츠 미리보기 부분에서 크래시가 날텐데

코드를 다음과 같이 코드 블럭으로 감싸시면 해결 될 것입니다.


~~~
```xml
<constructor-arg index="0" ref="sqlSessionFactory" />
```
~~~
