### ISSUE TITLE
글쓰기 후 저장 시 CORS 메세지

### ISSUE THREAD

**Issue by NaLDo627** [velopert/velog-client#94]
포스팅 창을 좀 오래 열어둔 상태(한 3시간 정도)에서, 내용을 입력하고 출간하기 버튼을 눌렀는데, 아래와 같은 이미지가 뜨면서 내가 쓴 글 페이지로 넘어가지 않습니다.

![스크린샷 2020-02-24 오후 4 41 25](https://user-images.githubusercontent.com/36787678/75135498-05be8580-5725-11ea-9ab5-b788b8350683.png)

그 상태에서 제 블로그로 넘어와 보니, 포스팅이 등록은 되어 있는 것을 확인할 수 있었습니다. 그러나 수정 시에도 똑같은 문제가 발생합니다.

**Comment by velopert** [comment]
혹시 동일한 이슈가 다시 발생하게 된다면 Network -> Response 쪽에서 오류난 graphql 응답의 결과물을 찍어주시면 감사하겠습니다!
