### ISSUE TITLE
검색 기능 사용시 유저의 현재 닉네임 매칭이 안됨

### ISSUE THREAD

**Issue by delmaSong** [velopert/velog-client#96]
궁금한 블로그가 있어 유저의 닉네임으로 검색해 들어가는데,
해당 유저가 닉네임을 변경했다면
변경한걸로 검색이 안되고, 이전에 설정했던 닉네임으로만 검색이 됩니다
수정 부탁드려요!

**Comment by charmmming7** [comment]
저도 오늘 유저명을 변경했는데, 바로 적용이 안되더라구요. 링크도 연결되지 않고,, 캐시 지우니 이 문제는 해결된 것 같습니다.
다만 id와 유저명(설정>info-area>h2)이 각각 존재하는건지 궁금합니다. 별도라면 혹시 id (velog 주소)를 변경할 수 없는건가요?

**Comment by velopert** [comment]
안녕하세요! 이 이슈는 서버쪽 이슈라 서버측에 새로 이슈 만들고 이 이슈는 close 하겠습니다.
질문주신 사항에 답변을 드리자면..

@delmaSong 
유저가 닉네임 변경 시에 ElasticSearch 쪽에서 싱크를 맞춰야하는데 이는 이후 주기적으로 싱크를 맞추는 작업을 진행하게 될 것 같습니다. 최근, 조횟수 * 10 또는 Like 에 따라서 검색엔진에 있는 포스트를 업데이트 하는 기능이 도입되어 어느정도 해결 되긴 했을텐데, 근본적인 문제가 해결된건 아니여서.. 추후 완벽히 고쳐지게 될 것 같습니다.

@charmmming7 

username 과 display_name 이라는 값이 있습니다. username은 주소에서 https://velog.io/@_______ 이런식으로 보여지는 형태인데요, 이를 바꾸는 기능은 아직 계획 상에 없습니다. 언제가 될 진 모르겠지만, 도입 해야 할 필요는 있을 것 같기는 하네요.. 하지만 당장은 모르겠습니다. 

display_name은 프로필 정보에서만 보여지는 값입니다.
