### ISSUE TITLE
블로그 팔로우 기능 필요

### ISSUE THREAD

**Issue by delmaSong** [velopert/velog-client#97]
블로그 팔로우 기능이 있다면 궁금한 유저의 블로그에 들어갈때
일일히 닉네임 or 블로그 이름을 기억하고 들어가지 않아도 될 것 같아요
팔로우 기능이 있으면 좋겠습니다.!

**Comment by velopert** [comment]
#62 
비슷한 이슈가 있어서 닫아놓겠습니다.
팔로우 기능, 구현 할 수 있도록 백엔드에서 DB설계도 되어있긴 한데..
아마... 올해 안엔 개발 되지 않을까 싶네요 하하하하
