### ISSUE TITLE
댓글 알림 기능이 필요합니다

### ISSUE THREAD

**Issue by delmaSong** [velopert/velog-client#98]
블로그에 댓글이 달리면 내용 보강도 하고 소통도 하며 벨로그가 더욱 적극적인 소통의 장이 되리라 생각합니다.
현재는 댓글이 달려도 화면 내에서 어떤 알림도 없기에 소통하기에 어려움이 있습니다.
많이 바쁘시겠지만 이 점또한 고려해주시면 감사하겠습니다!

**Comment by velopert** [comment]
고려하고 있습니다 :) 

원래는 이메일로 알림이 갔었는데.. 이번 업데이트해서 사라졌어요
다시 구현할 예정이고
서비스내 알림도 추후 구현 예정입니다!

감사합니다.

**Comment by velopert** [comment]
구현됐어요~

**Comment by delmaSong** [comment]
우와 감사합니다
