### ISSUE TITLE
출간하기가 되지 않습니다.

### ISSUE THREAD

**Issue by sooz1n** [velopert/velog-client#99]
게시글 작성 혹은 수정 후 출간을 하려고 하면 마지막 페이지(아래 이미지)에서 작동이 되지 않습니다.
![image](https://user-images.githubusercontent.com/59785548/75621597-d0f57700-5bd9-11ea-8bd1-dba16ad1b464.png)

좋은 블로그 만들어 주셔서 항상 감사합니다!

**Comment by velopert** [comment]
안녕하세요!
해당 오류가 발생했을 때, 혹시 어떤 태그를 설정하셨는지 알려주실 수 있을까요?

**Comment by sooz1n** [comment]
R, 크롤링
=> 이렇게 두개로 시도했습니다. R 이라는 태그 때문에 그런것 같기도 하네요.. ^^;

**Comment by velopert** [comment]
확실하진 않지만... 왠지 이유를 찾은 것 같아서 이전에 고쳐놨습니다.
혹시나 또 R 로 태그를 작성했는데 오류 발생하면 이슈 다시 열어주세요 또 검토해볼게요.
